<?php
  define('XPLANKONVERTER_SHAPE_PATH', UPLOADPATH . 'xplanshapes/');
  define('XPLANKONVERTER_KONVERTIERUNGEN_LAYER_ID', 8);
  define('XPLANKONVERTER_SHAPEFILES_LAYER_ID', 10);
	define('XPLANKONVERTER_VALIDIERUNGSERGEBNISSE_LAYER_ID' , 455);
?>