<?php
  define('XPLANKONVERTER_FILE_PATH', UPLOADPATH . 'xplankonverter/');
  define('XPLANKONVERTER_KONVERTIERUNGEN_LAYER_ID', 8);
  define('XPLANKONVERTER_SHAPEFILES_LAYER_ID', 10);
  define('XPLANKONVERTER_BP_PLAENE_LAYER_ID', 20);
  define('XPLANKONVERTER_FP_PLAENE_LAYER_ID', 22);
  define('XPLANKONVERTER_SO_PLAENE_LAYER_ID', 24);
  define('XPLANKONVERTER_RP_PLAENE_LAYER_ID', 26);
  define('XPLANKONVERTER_XP_PLAENE_LAYER_ID', 0);
  define('XPLANKONVERTER_BP_BEREICHE_LAYER_ID', 19);
  define('XPLANKONVERTER_FP_BEREICHE_LAYER_ID', 21);
  define('XPLANKONVERTER_SO_BEREICHE_LAYER_ID', 23);
  define('XPLANKONVERTER_RP_BEREICHE_LAYER_ID', 13);
  define('XPLANKONVERTER_XP_BEREICHE_LAYER_ID', 0);
  define('XPLANKONVERTER_REGELN_LAYER_ID', 9);
	define('XPLANKONVERTER_VALIDIERUNGSERGEBNISSE_LAYER_ID' , 455);
	define('GML_LAYER_TEMPLATE_GROUP', 10004);

	define('XPLANKONVERTER_CONTENT_SCHEMA', 'xplan_gml');

	define('XPLANKONVERTER_INSPIRE_KONVERTER', false);

	// Konstanten fuer GML-Builder
	// XML-namespace
	define('XPLAN_NS_PREFIX', 'xplan');
	define('XPLAN_NS_URI', "http://www.xplanung.de/xplangml/5/0");
	define('XPLAN_NS_SCHEMA_LOCATION', "http://www.xplanungwiki.de/upload/XPlanGML/5.0/Schema/XPlanung-Operationen.xsd");
	// max Rekursionstiefe für Nested Composite Types
	define ('XPLAN_MAX_NESTING_DEPTH', 3);
?>