<?php
  define('XPLANKONVERTER_SHAPE_PATH', UPLOADPATH . 'xplanshapes/');
  define('XPLANKONVERTER_KONVERTIERUNGEN_LAYER_ID', 8);
  define('XPLANKONVERTER_SHAPEFILES_LAYER_ID', 10);
  define('XPLANKONVERTER_PLAENE_LAYER_ID', 2);
  define('XPLANKONVERTER_BEREICHE_LAYER_ID', 3);
  define('XPLANKONVERTER_REGELN_LAYER_ID', 9);
	define('XPLANKONVERTER_VALIDIERUNGSERGEBNISSE_LAYER_ID' , 455);
	define('GML_LAYER_TEMPLATE_GROUP', 10004);
?>