#!/bin/bash
# Installationsskript für Datenbankstruktur von kvwmap in Postgis

#
# Voraussetzungen/Vorarbeiten
# Ein Postgres version ab 4.7.3 ist installiert
# Zusätzlich ist PostGIS ab 1.0 mit GEOS und Proj Unterstützung installiert
# Zusätzlich ist eine Datenbank durch EDBS2WKT angelegt

# Das Skript wird aufgerufen mit folgenden Parametern in der Reihenfolge
# 1.) templatename Der Name der Datenbank, die PostGIS Unterstützung hat und die EDBS-Tabellen enthält.
      default = alkpostgistemplate
# 2.) Benutzername, unter dem die Anwendung auf die postgis-Datenbank zugreifen soll
      default = kvwmap
# 3.) Datenbankname, mit der die Anwendung in postgis interagiert.
      default = kvwmapsp+Versionsname
      
# Beispiel
# kvwmap_install_pg alkpostgistemplate kvwmap kvwmapsp144            

if [ "$1" == "" ]
then
  echo Aufruf: kvwmap_install_pg template user dbname.;
  echo Beispiel: kvwmap_install_pg alkpostgistemplate kvwmap kvwmapsp144;
  exit;
fi;

if [ "$2" == "" ]
then
  echo Das 2. Argument fehlt.;
  exit;
fi;

if [ "$3" == "" ]
then
  echo Das 3. Argument fehlt.;
  exit;
fi;

# Erzeugen eines neuen Benutzers
psql -c "CREATE USER $2 CREATEDB" -U postgres template1

# Erzeugen einer neuen Datenbank.
psql -c "CREATE DATABASE $3 WITH TEMPLATE = $1 OWNER = $2 ENCODING = 'LATIN1'" -U postgres template1;

# Hinzufuegen der Tabellen der Anwendung
psql -f postgis_install.sql -U $2 $3;
