-- Flaechenlayer "BORIS" für die Darstellung der BRWzonen

SET @group_id = 1;
SET @connection = 'user=xxxx password=xxxx dbname=kvwmapsp';
INSERT INTO layer (`Name`,`alias`,`Datentyp`,`Gruppe`,`pfad`,`maintable`,`Data`,`schema`,`document_path`,`tileindex`,`tileitem`,`labelangleitem`,`labelitem`,`labelmaxscale`,`labelminscale`,`labelrequires`,`connection`,`printconnection`,`connectiontype`,`classitem`,`filteritem`,`tolerance`,`toleranceunits`,`epsg_code`,`template`,`queryable`,`transparency`,`drawingorder`,`minscale`,`maxscale`,`offsite`,`ows_srs`,`wms_name`,`wms_server_version`,`wms_format`,`wms_connectiontimeout`,`wms_auth_username`,`wms_auth_password`,`wfs_geom`,`selectiontype`,`querymap`,`logconsume`,`processing`,`kurzbeschreibung`,`datenherr`,`metalink`,`privileg`) VALUES('BORIS','','2',@group_id,'SELECT oid, *, \'\' as bearbeitungslink FROM bw_zonen WHERE (1=1)','bw_zonen','the_geom from (select oid, the_geom, zonentyp from bw_boris_view) as foo using unique oid using srid=25833','','','','','','',NULL,NULL,'',@connection,'','6','zonentyp','','3','pixels','25833','Bodenrichtwerte.php','1',NULL,'444',NULL,NULL,'','EPSG:2398','BORIS MV','1.1.0','image/png','60','','','','','1','0','','','','','0');
SET @last_layer_id427=LAST_INSERT_ID();
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'ackerzahl','ackerzahl','bw_zonen','bw_zonen','varchar','','','1','7','Text','','Ackerzahl','','25','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'aufwuchs','aufwuchs','bw_zonen','bw_zonen','varchar','','','1','2','Text','','Aufwuchs','','27','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'basiskarte','basiskarte','bw_zonen','bw_zonen','varchar','','','1','8','Text','','Basiskarte','','11','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'baumassenzahl','baumassenzahl','bw_zonen','bw_zonen','varchar','','','1','9','Text','','Baumassenzahl','','20','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'bauweise','bauweise','bw_zonen','bw_zonen','varchar','','','1','2','Text','','Bauweise','','16','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'bearbeitungslink','bearbeitungslink','','','unknown','','',NULL,NULL,'dynamicLink', CONCAT('index.php?go=Bodenrichtwertformular_Aendern&layer_id=', @last_layer_id427, '&oid=$oid;Bodenrichtwertzone bearbeiten;no_new_window'),'Bearbeitung','','39','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'bedarfswert','bedarfswert','bw_zonen','bw_zonen','float4','','','1','24','Text','','Bedarfswert','','34','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'beitragszustand','beitragszustand','bw_zonen','bw_zonen','varchar','','','1','1','Text','','Beitragszustand','','13','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'bemerkungen','bemerkungen','bw_zonen','bw_zonen','varchar','','','1','256','Text','','Bemerkungen','','30','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'bodenart','bodenart','bw_zonen','bw_zonen','varchar','','','1','6','Text','','Bodenart','','35','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'bodenrichtwert','bodenrichtwert','bw_zonen','bw_zonen','float4','','','1','24','Text','','Bodenrichtwert','','9','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'bodenrichtwertnummer','bodenrichtwertnummer','bw_zonen','bw_zonen','int4','','','1','32','Text','','Bodenrichtwertnummer','','7','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'breite','breite','bw_zonen','bw_zonen','varchar','','','1','8','Text','','Breite','','23','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'brwb','brwb','bw_zonen','bw_zonen','float4','','','1','24','Text','','brwb','','38','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'brws','brws','bw_zonen','bw_zonen','float4','','','1','24','Text','','brws','','37','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'brwu','brwu','bw_zonen','bw_zonen','float4','','','1','24','Text','','brwu','','36','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'entwicklungszustand','entwicklungszustand','bw_zonen','bw_zonen','varchar','','','1','2','Text','','Entwicklungszustand','','12','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'ergaenzende_nutzung','ergaenzende_nutzung','bw_zonen','bw_zonen','varchar','','','1','30','Text','','Ergaenzende_nutzung','','15','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'erschliessungsverhaeltnisse','erschliessungsverhaeltnisse','bw_zonen','bw_zonen','int4','','','1','32','Text','','Erschliessungsverhaeltnisse','','33','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'flaeche','flaeche','bw_zonen','bw_zonen','varchar','','','1','12','Text','','Flaeche','','21','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'gemarkung','gemarkung','bw_zonen','bw_zonen','int4','','','1','32','Auswahlfeld','select gemkgschl as value, gemkgname as output from alb_v_gemarkungen as g WHERE g.gemeinde = <requires>gemeinde</requires>','Gemarkung','','2','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'gemeinde','gemeinde','bw_zonen','bw_zonen','int4','','','1','32','Auswahlfeld','select gemeinde as value, gemeindename as output from alb_v_gemeinden <required by>gemarkung</required by>','Gemeinde','','1','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'geschossflaechenzahl','geschossflaechenzahl','bw_zonen','bw_zonen','varchar','','','1','11','Text','','Geschossflaechenzahl','','19','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'geschosszahl','geschosszahl','bw_zonen','bw_zonen','varchar','','','1','9','Text','','Geschosszahl','','17','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'gruenlandzahl','gruenlandzahl','bw_zonen','bw_zonen','varchar','','','1','7','Text','','Gruenlandzahl','','26','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'grundflaechenzahl','grundflaechenzahl','bw_zonen','bw_zonen','varchar','','','1','9','Text','','Grundflaechenzahl','','18','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'gutachterausschuss','gutachterausschuss','bw_zonen','bw_zonen','int4','','','1','32','Text','','Gutachterausschuss','','6','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'nutzungsart','nutzungsart','bw_zonen','bw_zonen','varchar','','','1','7','Text','','Nutzungsart','','14','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'oertliche_bezeichnung','oertliche_bezeichnung','bw_zonen','bw_zonen','varchar','','','1','256','Text','','Örtliche_bezeichnung','','8','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'oid','oid','','','oid','','',NULL,NULL,'Text','','','','0','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'ortsteilname','ortsteilname','bw_zonen','bw_zonen','varchar','','','1','60','Text','','Ortsteilname','','3','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'postleitzahl','postleitzahl','bw_zonen','bw_zonen','int4','','','1','32','Text','','Postleitzahl','','4','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'stichtag','stichtag','bw_zonen','bw_zonen','date','','','1',NULL,'Text','','Stichtag','','10','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'textposition','textposition','bw_zonen','bw_zonen','geometry','POINT','','1',NULL,'Geometrie','','','','31','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'the_geom','the_geom','bw_zonen','bw_zonen','geometry','POLYGON','','1',NULL,'Geometrie','','','','32','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'tiefe','tiefe','bw_zonen','bw_zonen','varchar','','','1','8','Text','','Tiefe','','22','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'verfahrensgrund','verfahrensgrund','bw_zonen','bw_zonen','varchar','','','1','4','Text','','Verfahrensgrund','','28','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'verfahrensgrund_zusatz','verfahrensgrund_zusatz','bw_zonen','bw_zonen','varchar','','','1','2','Text','','Verfahrensgrund_zusatz','','29','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'wegeerschliessung','wegeerschliessung','bw_zonen','bw_zonen','varchar','','','1','1','Text','','Wegeerschliessung','','24','0');
INSERT INTO layer_attributes (`layer_id`,`name`,`real_name`,`tablename`,`table_alias_name`,`type`,`geometrytype`,`constraints`,`nullable`,`length`,`form_element_type`,`options`,`alias`,`tooltip`,`order`,`privileg`) VALUES(@last_layer_id427,'zonentyp','zonentyp','bw_zonen','bw_zonen','varchar','','','1','256','Text','','Zonentyp','','5','0');
INSERT INTO classes (`Name`,`Layer_ID`,`Expression`,`drawingorder`,`text`) VALUES('alle',@last_layer_id427,'','1','');
SET @last_class_id=LAST_INSERT_ID();
INSERT INTO styles (`symbol`,`symbolname`,`size`,`color`,`backgroundcolor`,`outlinecolor`,`minsize`,`maxsize`,`angle`,`angleitem`,`antialias`,`width`,`minwidth`,`maxwidth`,`sizeitem`) VALUES('9','','2','-1 -1 -1','','224 92 14','2','4','360','',NULL,NULL,NULL,NULL,'');
 SET @last_style_id=LAST_INSERT_ID();
INSERT INTO u_styles2classes (style_id, class_id, drawingorder) VALUES (@last_style_id, @last_class_id, 0);


-- Punktlayer "BORIS_T" für die Anzeige des Labels an der Textposition

SET @group_id = 1;
SET @connection = 'user=xxxx password=xxxx dbname=kvwmapsp';
INSERT INTO layer (`Name`,`Datentyp`,`Gruppe`,`pfad`,`Data`,`schema`,`tileindex`,`tileitem`,`labelangleitem`,`labelitem`,`labelmaxscale`,`labelminscale`,`labelrequires`,`connection`,`printconnection`,`connectiontype`,`classitem`,`filteritem`,`tolerance`,`toleranceunits`,`epsg_code`,`template`,`queryable`,`transparency`,`drawingorder`,`minscale`,`maxscale`,`offsite`,`ows_srs`,`wms_name`,`wms_server_version`,`wms_format`,`wms_connectiontimeout`,`wfs_geom`,`selectiontype`,`querymap`,`logconsume`) VALUES('BORIS_T','0',@group_id,'SELECT * FROM bw_boris_view WHERE (1=1)','textposition from (select * from bw_boris_view) as foo using unique oid using srid=25833','','','','','bw_darstellung','30000','1','',@connection,NULL,'6','oid','','3','pixels','25833','','0',NULL,NULL,NULL,NULL,'','EPSG:25833','BORIS MV','1.1.0','image/png','60','','','0','');
SET @last_layer_id=LAST_INSERT_ID();
INSERT INTO classes (`Name`,`Layer_ID`,`Expression`,`drawingorder`,`text`) VALUES('alle',@last_layer_id,NULL,'1','');
SET @last_class_id=LAST_INSERT_ID();
INSERT INTO styles (`symbol`,`symbolname`,`size`,`color`,`backgroundcolor`,`outlinecolor`,`minsize`,`maxsize`,`angle`,`angleitem`,`antialias`,`width`,`minwidth`,`maxwidth`,`sizeitem`) VALUES(NULL,'','1','','','',NULL,'1','360','',NULL,NULL,NULL,NULL,'');
SET @last_style_id=LAST_INSERT_ID();
INSERT INTO u_styles2classes (style_id, class_id) VALUES (@last_style_id, @last_class_id);
INSERT INTO labels (`font`,`type`,`color`,`outlinecolor`,`shadowcolor`,`shadowsizex`,`shadowsizey`,`backgroundcolor`,`backgroundshadowcolor`,`backgroundshadowsizex`,`backgroundshadowsizey`,`size`,`minsize`,`maxsize`,`position`,`offsetx`,`offsety`,`angle`,`autoangle`,`buffer`,`antialias`,`minfeaturesize`,`maxfeaturesize`,`partials`,`wrap`,`the_force`) VALUES('arial_bold',NULL,'224 92 14','255 255 255','',NULL,NULL,'255 255 255','',NULL,NULL,'10','10','15',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
SET @last_label_id=LAST_INSERT_ID();
INSERT INTO u_labels2classes (label_id, class_id) VALUES (@last_label_id, @last_class_id);