BEGIN;

  ALTER TABLE `user` CHANGE `phon` `phon` VARCHAR(25) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;
  ALTER TABLE `user` CHANGE `email` `email` VARCHAR(100) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL;

COMMIT;
