BEGIN;
	ALTER TABLE `rolle` CHANGE `nImageWidth` `nImageWidth` INT(3) NOT NULL DEFAULT '800';
	ALTER TABLE `rolle` CHANGE `nImageHeight` `nImageHeight` INT(3) NOT NULL DEFAULT '600';
	ALTER TABLE `rolle` CHANGE `epsg_code` `epsg_code` VARCHAR(6) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT '25833';
	ALTER TABLE `rolle` CHANGE `minx` `minx` DOUBLE NOT NULL DEFAULT '201165';
	ALTER TABLE `rolle` CHANGE `miny` `miny` DOUBLE NOT NULL DEFAULT '5867815';
	ALTER TABLE `rolle` CHANGE `maxx` `maxx` DOUBLE NOT NULL DEFAULT '477900';
	ALTER TABLE `rolle` CHANGE `maxy` `maxy` DOUBLE NOT NULL DEFAULT '6081468';
	ALTER TABLE `rolle` CHANGE `singlequery` `singlequery` TINYINT(1) NOT NULL DEFAULT '1';
	ALTER TABLE `rolle` CHANGE `instant_reload` `instant_reload` TINYINT(1) NOT NULL DEFAULT '1';
	ALTER TABLE `rolle` CHANGE `showmapfunctions` `showmapfunctions` TINYINT(1) NOT NULL DEFAULT '1' COMMENT 'Schaltet die Menüleiste mit den Kartenfunktionen unter der Karte ein oder aus.';
COMMIT;
