ALTER TABLE classes CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE classes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE colors CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE colors CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE config CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE config CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE connections CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE connections CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE cron_jobs CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE cron_jobs CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE datatype_attributes CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE datatype_attributes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE datatypes CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE datatypes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE datendrucklayouts CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE datendrucklayouts CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ddl2freilinien CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ddl2freilinien CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ddl2freirechtecke CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ddl2freirechtecke CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ddl2freitexte CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ddl2freitexte CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ddl2stelle CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ddl2stelle CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ddl_colors CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ddl_colors CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ddl_elemente CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE ddl_elemente CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckausschnitte CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckausschnitte CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckfreibilder CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckfreibilder CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckfreilinien CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckfreilinien CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckfreirechtecke CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckfreirechtecke CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckfreitexte CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckfreitexte CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckrahmen CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckrahmen CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckrahmen2freibilder CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckrahmen2freibilder CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckrahmen2freitexte CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckrahmen2freitexte CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckrahmen2stelle CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE druckrahmen2stelle CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE invitations CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE invitations CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE labels CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE labels CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE layer CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE layer CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE layer_attributes CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE layer_attributes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE layer_attributes2stelle CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE layer_attributes2stelle CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE layer_parameter CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE layer_parameter CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE migrations CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE migrations CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE referenzkarten CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE referenzkarten CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE rolle CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE rolle CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE rolle_csv_attributes CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE rolle_csv_attributes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE rolle_last_query CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE rolle_last_query CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
#ALTER TABLE rolle_nachweise CHARACTER SET utf8 COLLATE utf8_general_ci;
#ALTER TABLE rolle_nachweise CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
#ALTER TABLE rolle_nachweise_dokumentauswahl CHARACTER SET utf8 COLLATE utf8_general_ci;
#ALTER TABLE rolle_nachweise_dokumentauswahl CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE rolle_saved_layers CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE rolle_saved_layers CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE rollenlayer CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE rollenlayer CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE search_attributes2rolle CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE search_attributes2rolle CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE sicherungen CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE sicherungen CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE sicherungsinhalte CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE sicherungsinhalte CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE stelle CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE stelle CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE stelle_gemeinden CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE stelle_gemeinden CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE stellen_hierarchie CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE stellen_hierarchie CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE styles CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE styles CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_attributfilter2used_layer CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_attributfilter2used_layer CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_consume CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_consume CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_consume2comments CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_consume2comments CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_consume2layer CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_consume2layer CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_consumeALB CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_consumeALB CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_consumeALK CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_consumeALK CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_consumeCSV CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_consumeCSV CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
#ALTER TABLE u_consumeNachweise CHARACTER SET utf8 COLLATE utf8_general_ci;
#ALTER TABLE u_consumeNachweise CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_consumeShape CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_consumeShape CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_funktion2stelle CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_funktion2stelle CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_funktionen CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_funktionen CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_groups CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_groups CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_groups2rolle CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_groups2rolle CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_labels2classes CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_labels2classes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_menue2rolle CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_menue2rolle CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_menue2stelle CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_menue2stelle CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_menues CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_menues CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_rolle2used_class CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_rolle2used_class CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_rolle2used_layer CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_rolle2used_layer CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_styles2classes CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE u_styles2classes CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE used_layer CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE used_layer CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE user CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE user CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE zwischenablage CHARACTER SET utf8 COLLATE utf8_general_ci;
ALTER TABLE zwischenablage CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;