BEGIN;

UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '002' WHERE langtext = 'Balken';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '003' WHERE langtext = 'Barren';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '004' WHERE langtext = 'Basketballkorb';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '005' WHERE langtext = 'Betonröhre';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '006' WHERE langtext = 'BMX-Bahn';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '007' WHERE langtext = 'Bock';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '008' WHERE langtext = 'Boot';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '009' WHERE langtext = 'Doppelschaukel';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '010' WHERE langtext = 'Drehkarussell';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '011' WHERE langtext = 'Drehpfosten';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '012' WHERE langtext = 'Drehscheibe';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '013' WHERE langtext = 'EDGE';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '014' WHERE langtext = 'Federbank';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '015' WHERE langtext = 'Federschaukel';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '016' WHERE langtext = 'Funbox';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '017' WHERE langtext = 'Fußballtor';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '018' WHERE langtext = 'Grindstange';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '019' WHERE langtext = 'Hängestange';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '020' WHERE langtext = 'Holzfisch';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '021' WHERE langtext = 'Hundewippe';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '022' WHERE langtext = 'Hüpfplatte';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '023' WHERE langtext = 'Karussell';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '024' WHERE langtext = 'Kinderspielbank';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '025' WHERE langtext = 'Kletterburg';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '026' WHERE langtext = 'Klettergerüst';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '027' WHERE langtext = 'Klettergerüst mit Netz';
UPDATE ukos_base.wld_objektbezeichnung SET langtext = 'Klettergerüst mit Rutsche und Doppelschaukel', sortierreihenfolge = '028' WHERE langtext = 'Klettergerüst mit Rutsche u. Doppelschaukel';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '029' WHERE langtext = 'Klettergerüst und Tischtennisplatte';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '030' WHERE langtext = 'Kletternetz';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '031' WHERE langtext = 'Kletterseil';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '032' WHERE langtext = 'Kletterstange';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '033' WHERE langtext = 'Kombi-Spielgerät';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '034' WHERE langtext = 'Kombi-Spielgerät mit Rutsche';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '035' WHERE langtext = 'Kombi-Spielgerät mit Schaukel';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '036' WHERE langtext = 'Kugelstoßanlage';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '037' WHERE langtext = 'Magische Hecke';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '038' WHERE langtext = 'Maltafel';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '039' WHERE langtext = 'Pavillon';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '040' WHERE langtext = 'Quaterpipe';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '041' WHERE langtext = 'Reck';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '042' WHERE langtext = 'Reckstange';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '043' WHERE langtext = 'Reifen';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '044' WHERE langtext = 'Reifenschwinger';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '045' WHERE langtext = 'Rutsche';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '046' WHERE langtext = 'Rutsche, Seilbahn';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '047' WHERE langtext = 'Rutschturm';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '048' WHERE langtext = 'Sandkasten';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '049' WHERE langtext = 'Sandschiff';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '050' WHERE langtext = 'Schaukel';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '051' WHERE langtext = 'Schaukelnest';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '052' WHERE langtext = 'Schaukel, Spinne';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '053' WHERE langtext = 'Schwebebalken';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '054' WHERE langtext = 'Seilbahn';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '055' WHERE langtext = 'Spielhaus';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '056' WHERE langtext = 'Spinnennetz';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '057' WHERE langtext = 'Spinnennetz und Liege';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '058' WHERE langtext = 'Spinnennetz und Schaukel';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '059' WHERE langtext = 'Strickschaukel';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '060' WHERE langtext = 'Supernova';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '061' WHERE langtext = 'Tafel';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '062' WHERE langtext = 'Tellersitzwippe';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '063' WHERE langtext = 'Tischtennisplatte';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '064' WHERE langtext = 'Tor';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '065' WHERE langtext = 'Torwand';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '066' WHERE langtext = 'Trampolin';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '067' WHERE langtext = 'Umlaufender Holzsteg';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '068' WHERE langtext = 'Vogelnestschaukel';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '069' WHERE langtext = 'Volleyballfeld';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '070' WHERE langtext = 'Volleyballnetz';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '071' WHERE langtext = 'Wackelsteg';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '072' WHERE langtext = 'Weitsprunganlage';
UPDATE ukos_base.wld_objektbezeichnung SET sortierreihenfolge = '073' WHERE langtext = 'Wippschaukel';


COMMIT;
