BEGIN;

UPDATE ukos_base.wld_deckschicht SET sortierreihenfolge = '002' WHERE langtext = 'Beton';
UPDATE ukos_base.wld_deckschicht SET sortierreihenfolge = '003' WHERE langtext = 'bituminös';
UPDATE ukos_base.wld_deckschicht SET sortierreihenfolge = '004' WHERE langtext = 'Pflaster';
UPDATE ukos_base.wld_deckschicht SET sortierreihenfolge = '005' WHERE langtext = 'sonstiges';
UPDATE ukos_base.wld_deckschicht SET sortierreihenfolge = '006' WHERE langtext = 'unbefestigt';

UPDATE ukos_base.wld_zustandsbewertung SET sortierreihenfolge = '002' WHERE langtext = '100% (nicht ausgeprägt)';
UPDATE ukos_base.wld_zustandsbewertung SET sortierreihenfolge = '003' WHERE langtext = '65% (ausgeprägt)';
UPDATE ukos_base.wld_zustandsbewertung SET sortierreihenfolge = '004' WHERE langtext = '30% (stark ausgeprägt)';
UPDATE ukos_base.wld_zustandsbewertung SET sortierreihenfolge = '005' WHERE langtext = '0%';

UPDATE ukos_base.wld_zustand SET sortierreihenfolge = '002' WHERE langtext = '1';
UPDATE ukos_base.wld_zustand SET sortierreihenfolge = '003' WHERE langtext = '2';
UPDATE ukos_base.wld_zustand SET sortierreihenfolge = '004' WHERE langtext = '3';
UPDATE ukos_base.wld_zustand SET sortierreihenfolge = '005' WHERE langtext = '4';
UPDATE ukos_base.wld_zustand SET sortierreihenfolge = '005' WHERE langtext = '5';

UPDATE ukos_base.wld_preisermittlung SET langtext = 'geschätzt', sortierreihenfolge = '002' WHERE langtext = 'Geschätzt';
UPDATE ukos_base.wld_preisermittlung SET langtext = 'Rechnungsnummer 01', sortierreihenfolge = '003' WHERE langtext = 'Rechnnr. 01';
UPDATE ukos_base.wld_preisermittlung SET langtext = 'Rechnungsnummer 02', sortierreihenfolge = '004' WHERE langtext = 'Rechnnr. 02';
UPDATE ukos_base.wld_preisermittlung SET sortierreihenfolge = '005' WHERE langtext = 'Einzelwert';

UPDATE ukos_base.wld_eigentuemer SET sortierreihenfolge = '002' WHERE kurztext = 'B';
UPDATE ukos_base.wld_eigentuemer SET sortierreihenfolge = '003' WHERE kurztext = 'L';
UPDATE ukos_base.wld_eigentuemer SET sortierreihenfolge = '004' WHERE kurztext = 'K';
UPDATE ukos_base.wld_eigentuemer SET sortierreihenfolge = '005' WHERE kurztext = 'G';
UPDATE ukos_base.wld_eigentuemer SET langtext = 'privat', sortierreihenfolge = '006' WHERE langtext = 'Privat';
UPDATE ukos_base.wld_eigentuemer SET sortierreihenfolge = '007' WHERE kurztext = 'rsag';
UPDATE ukos_base.wld_eigentuemer SET sortierreihenfolge = '008' WHERE kurztext = 'sr';
UPDATE ukos_base.wld_eigentuemer SET kurztext = 'ZVG', langtext = 'Zweckverband Grevesmühlen', sortierreihenfolge = '009' WHERE langtext = 'ZVG';

UPDATE ukos_base.wld_fertigstellung SET langtext = 'fertiggestellt', sortierreihenfolge = '002' WHERE langtext = 'Fertiggestellt';
UPDATE ukos_base.wld_fertigstellung SET langtext = 'im Bau', sortierreihenfolge = '003' WHERE langtext = 'Im Bau';
UPDATE ukos_base.wld_fertigstellung SET langtext = 'unbestimmt', sortierreihenfolge = '004' WHERE langtext = 'Unbestimmt';
UPDATE ukos_base.wld_fertigstellung SET langtext = 'zum Abgang', sortierreihenfolge = '005' WHERE langtext = 'Zum Abgang';

UPDATE ukos_base.wld_material SET sortierreihenfolge = '002' WHERE langtext = 'Beton';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '003' WHERE langtext = 'Draht';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '004' WHERE langtext = 'Drainage';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '005' WHERE langtext = 'Erde';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '006' WHERE langtext = 'Gestein';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '007' WHERE langtext = 'Glas';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '008' WHERE langtext = 'Granit';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '009' WHERE langtext = 'Gummi';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '010' WHERE langtext = 'Holz';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '011' WHERE langtext = 'Holz/Granit';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '012' WHERE langtext = 'Holz/Kunststoff';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '013' WHERE langtext = 'Kunststoff';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '014' WHERE langtext = 'Materialmix';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '015' WHERE langtext = 'Metall';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '016' WHERE langtext = 'Metall/Glas';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '017' WHERE langtext = 'Metall/Granit';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '018' WHERE langtext = 'Metall/Holz';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '019' WHERE langtext = 'Metall/Kunststoff';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '020' WHERE langtext = 'Metall/Stein';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '021' WHERE langtext = 'Naturstein';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '022' WHERE langtext = 'Pflaster';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '023' WHERE langtext = 'PVC';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '024' WHERE langtext = 'Stein';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '025' WHERE langtext = 'Stein/Glas';
UPDATE ukos_base.wld_material SET sortierreihenfolge = '026' WHERE langtext = 'Stein/Holz';

DELETE FROM ukos_base.wld_baumart WHERE langtext = 'Unbekannt';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '002' WHERE langtext = 'Ahorn';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '003' WHERE langtext = 'Akazie';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '004' WHERE langtext = 'Apfelbaum';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '005' WHERE langtext = 'Birke';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '006' WHERE langtext = 'Buche';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '007' WHERE langtext = 'Bergahorn';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '008' WHERE langtext = 'Birnbaum';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '009' WHERE langtext = 'Blautanne';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '010' WHERE langtext = 'Eberesche';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '011' WHERE langtext = 'Eiche';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '012' WHERE langtext = 'Erle';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '013' WHERE langtext = 'Esche';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '014' WHERE langtext = 'Essigbaum';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '015' WHERE langtext = 'Eibe';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '016' WHERE langtext = 'Esskastanie';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '017' WHERE langtext = 'Fichte';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '018' WHERE langtext = 'Flieder';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '019' WHERE langtext = 'Gemeine Robinie';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '020' WHERE langtext = 'Ginko';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '021' WHERE langtext = 'Goldregen';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '022' WHERE langtext = 'Gemeine Eberesche';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '023' WHERE langtext = 'Ginster';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '024' WHERE langtext = 'Haselnuss';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '025' WHERE langtext = 'Hagebutte';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '026' WHERE langtext = 'Holunder';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '027' WHERE langtext = 'Japanische Wildkirsche';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '028' WHERE langtext = 'Kiefer';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '029' WHERE langtext = 'Kirschbaum';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '030' WHERE langtext = 'Kastanie';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '031' WHERE langtext = 'Linde';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '032' WHERE langtext = 'Laubbaum';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '033' WHERE langtext = 'Lederhülsenbaum';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '034' WHERE langtext = 'Lärche';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '035' WHERE langtext = 'Mehlbeere';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '036' WHERE langtext = 'Mahonie';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '037' WHERE langtext = 'Nadelgehölz';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '038' WHERE langtext = 'Nadelbaum';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '039' WHERE langtext = 'Nussbaum';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '040' WHERE langtext = 'Obstbaum';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '041' WHERE langtext = 'Platane';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '042' WHERE langtext = 'Pappel';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '043' WHERE langtext = 'Pflaumenbaum';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '044' WHERE langtext = 'Pinie';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '045' WHERE langtext = 'Robinie';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '046' WHERE langtext = 'Rotdorn';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '047' WHERE langtext = 'Rotbuche';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '048' WHERE langtext = 'Roteiche';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '049' WHERE langtext = 'Silberweide';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '050' WHERE langtext = 'Sanddorn';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '051' WHERE langtext = 'Sauerkirschbaum';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '052' WHERE langtext = 'Schlehe';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '053' WHERE langtext = 'Schwarz-Erle';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '054' WHERE langtext = 'Spitzpappel';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '055' WHERE langtext = 'Stieleiche';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '056' WHERE langtext = 'Tanne';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '057' WHERE langtext = 'Trauerweide';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '058' WHERE langtext = 'Ulme';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '059' WHERE langtext = 'Vogelbeere';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '060' WHERE langtext = 'Weide';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '061' WHERE langtext = 'Weißdorn';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '062' WHERE langtext = 'Walnußbaum';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '063' WHERE langtext = 'Wildapfelbaum';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '064' WHERE langtext = 'Wildkirsche';
UPDATE ukos_base.wld_baumart SET sortierreihenfolge = '065' WHERE langtext = 'Wildobstbaum';

DELETE FROM ukos_base.wld_objektbezeichnung WHERE id NOT IN (SELECT max(duplikate.id) FROM ukos_base.wld_objektbezeichnung AS duplikate GROUP BY langtext);

COMMIT;
