BEGIN;

-- BP_BaugebietsTeilFlaeche
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN dnmin double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN dnmax double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN dn double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN dnzwingend double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN fr double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN dachform xplan_gml.bp_dachform[];
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN detailliertedachform xplan_gml.bp_detaildachform[];
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN maxzahlwohnungen integer;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN fmin double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN fmax double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN bmin double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN bmax double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN tmin double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN tmax double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN gfzmin double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN gfzmax double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN gfz double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN gfz_ausn double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN gfmin double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN gfmax double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN gf double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN gf_ausn double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN bmz double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN bmz_ausn double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN bm double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN bm_ausn double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN grzmin double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN grzmax double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN grz double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN grz_ausn double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN grmin double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN grmax double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN gr double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN gr_ausn double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN zmin integer;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN zmax integer;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN zzwingend integer;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN z integer;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN z_ausn integer;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN z_staffel integer;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN z_dach integer;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN zumin integer;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN zumax integer;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN zuzwingend integer;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN zu integer;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN zu_ausn integer;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN wohnnutzungegstrasse xplan_gml.bp_zulaessigkeit;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN zwohn integer;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN gfantwohnen double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN gfwohnen double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN gfantgewerbe double precision;
ALTER TABLE xplan_gml.bp_baugebietsteilflaeche ADD COLUMN gfgewerbe double precision;

COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.dnmin IS 'Ableitung von Type BP_GestaltungBaugebiet DNMin AngleType double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.dnmax IS 'Ableitung von Type BP_GestaltungBaugebiet double precision; DNMin AngleType double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.dn IS 'Ableitung von Type BP_GestaltungBaugebiet double precision; DN AngleType double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.dnzwingend IS 'Ableitung von Type BP_GestaltungBaugebiet DN AngleType double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.fr IS 'Ableitung von Type BP_GestaltungBaugebiet  DN AngleType double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.dachform IS 'Ableitung von Type BP_GestaltungBaugebiet xplan_gml.bp_dachform[] dachform enumeration xplan_gml.bp_dachform[] 0..*';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.detailliertedachform IS 'Ableitung von Type BP_GestaltungBaugebiet xplan_gml.bp_detaildachform[] detaillierteDachform CodeList BP_DetailDachform 0..*';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.maxzahlwohnungen IS 'Ableitung von Type BP_FestsetzungenBaugebiet, MaxZahlWohnungen integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.fmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.fmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.bmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.bmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.tmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.tmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.gfzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.gfzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.gfz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.gfz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.gfmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.gfmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.gf IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.gf_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.bmz IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.bmz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.bm IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.bm_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.grzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.grzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.grz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.grz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.grmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.grmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.gr IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.gr_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.zmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.zmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.zzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zzwingend integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.z IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.z_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Ausn integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.z_staffel IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Staffel integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.z_dach IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Dach integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.zumin IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.zumax IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.zuzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet integerZUzwingend 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.zu IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu integer0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.zu_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu_ausn integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.wohnnutzungegstrasse IS 'Ableitung von Type BP_ZusaetzlicheFestsetzungen xplan_gml.bp_zulaessigkeit wohnnutzungEGStrasse enumeration xplan_gml.BP_Zulaessigkeit 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.zwohn IS 'Ableitung von Type BP_ZusaetzlicheFestsetzungen integer ZWohn integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.gfantwohnen IS 'Ableitung von Type BP_ZusaetzlicheFestsetzungen double precision GFAntwWohnen double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.gfwohnen IS 'Ableitung von Type BP_ZusaetzlicheFestsetzungen double precision GFWohnen double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.gfantgewerbe IS 'Ableitung von Type BP_ZusaetzlicheFestsetzungen double precision GFAntGewerbe double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_baugebietsteilflaeche.gfgewerbe IS 'Ableitung von Type BP_ZusaetzlicheFestsetzungen double precision GFGewerbe double precision 0..1';

-- BP_BesondererNutzungszweckFlaeche
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN dnmin double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN dnmax double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN dn double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN dnzwingend double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN fr double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN dachform xplan_gml.bp_dachform[];
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN detailliertedachform xplan_gml.bp_detaildachform[];
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN maxzahlwohnungen integer;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN fmin double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN fmax double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN bmin double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN bmax double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN tmin double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN tmax double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN gfzmin double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN gfzmax double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN gfz double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN gfz_ausn double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN gfmin double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN gfmax double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN gf double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN gf_ausn double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN bmz double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN bmz_ausn double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN bm double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN bm_ausn double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN grzmin double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN grzmax double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN grz double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN grz_ausn double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN grmin double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN grmax double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN gr double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN gr_ausn double precision;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN zmin integer;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN zmax integer;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN zzwingend integer;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN z integer;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN z_ausn integer;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN z_staffel integer;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN z_dach integer;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN zumin integer;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN zumax integer;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN zuzwingend integer;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN zu integer;
ALTER TABLE xplan_gml.bp_besonderernutzungszweckflaeche ADD COLUMN zu_ausn integer;

COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.dnmin IS 'Ableitung von Type BP_GestaltungBaugebiet DNMin AngleType double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.dnmax IS 'Ableitung von Type BP_GestaltungBaugebiet DNMin AngleType double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.dn IS 'Ableitung von Type BP_GestaltungBaugebiet DN AngleType double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.dnzwingend IS 'Ableitung von Type BP_GestaltungBaugebiet DN AngleType double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.fr IS 'Ableitung von Type BP_GestaltungBaugebiet  DN AngleType double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.dachform IS 'Ableitung von Type BP_GestaltungBaugebiet xplan_gml.bp_dachform[] dachform enumeration xplan_gml.bp_dachform[] 0..*';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.detailliertedachform IS 'Ableitung von Type BP_FestsetzungenBaugebiet xplan_gml.bp_detaildachform[] detaillierteDachform CodeList BP_DetailDachform 0..*';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.maxzahlwohnungen IS 'Ableitung von Type BP_FestsetzungenBaugebiet, MaxZahlWohnungen integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.fmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.fmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.bmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.bmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.tmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.tmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.gfzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.gfzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.gfz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.gfz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.gfmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.gfmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.gf IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.gf_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.bmz IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.bmz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.bm IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.bm_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.grzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.grzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.grz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.grz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.grmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.grmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.gr IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.gr_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.zmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.zmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.zzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zzwingend integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.z IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.z_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Ausn integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.z_staffel IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Staffel integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.z_dach IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Dach integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.zumin IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.zumax IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.zuzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet integerZUzwingend 0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.zu IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu integer0..1';
COMMENT ON COLUMN xplan_gml.bp_besonderernutzungszweckflaeche.zu_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu_ausn integer 0..1';

-- BP_UeberbaubareGrundstuecksFlaeche
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN dnmin double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN dnmax double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN dn double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN dnzwingend double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN fr double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN dachform xplan_gml.bp_dachform[];
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN detailliertedachform xplan_gml.bp_detaildachform[];
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN maxzahlwohnungen integer;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN fmin double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN fmax double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN bmin double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN bmax double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN tmin double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN tmax double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN gfzmin double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN gfzmax double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN gfz double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN gfz_ausn double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN gfmin double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN gfmax double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN gf double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN gf_ausn double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN bmz double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN bmz_ausn double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN bm double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN bm_ausn double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN grzmin double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN grzmax double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN grz double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN grz_ausn double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN grmin double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN grmax double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN gr double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN gr_ausn double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN zmin integer;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN zmax integer;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN zzwingend integer;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN z integer;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN z_ausn integer;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN z_staffel integer;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN z_dach integer;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN zumin integer;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN zumax integer;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN zuzwingend integer;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN zu integer;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN zu_ausn integer;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN wohnnutzungegstrasse xplan_gml.bp_zulaessigkeit;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN zwohn integer;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN gfantwohnen double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN gfwohnen double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN gfantgewerbe double precision;
ALTER TABLE xplan_gml.bp_ueberbaubaregrundstuecksflaeche ADD COLUMN gfgewerbe double precision;

COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.dnmin IS 'Ableitung von Type BP_GestaltungBaugebiet DNMin AngleType double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.dnmax IS 'Ableitung von Type BP_GestaltungBaugebiet DNMin AngleType double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.dn IS 'Ableitung von Type BP_GestaltungBaugebiet DN AngleType double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.dnzwingend IS 'Ableitung von Type BP_GestaltungBaugebiet DN AngleType double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.fr IS 'Ableitung von Type BP_GestaltungBaugebiet  DN AngleType double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.dachform IS 'Ableitung von Type BP_GestaltungBaugebiet xplan_gml.bp_dachform[] dachform enumeration xplan_gml.bp_dachform[] 0..*';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.detailliertedachform IS 'Ableitung von Type BP_GestaltungBaugebiet xplan_gml.bp_detaildachform[] detaillierteDachform CodeList BP_DetailDachform 0..*';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.maxzahlwohnungen IS 'Ableitung von Type BP_FestsetzungenBaugebiet, MaxZahlWohnungen integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.fmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.fmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.bmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.bmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.tmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.tmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.gfzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.gfzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.gfz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.gfz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.gfmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.gfmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.gf IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.gf_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.bmz IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.bmz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.bm IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.bm_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.grzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.grzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.grz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.grz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.grmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.grmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.gr IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.gr_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.zmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.zmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.zzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zzwingend integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.z IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.z_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Ausn integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.z_staffel IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Staffel integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.z_dach IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Dach integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.zumin IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.zumax IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.zuzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet integerZUzwingend 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.zu IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu integer0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.zu_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu_ausn integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.wohnnutzungegstrasse IS 'xplan_gml.bp_zulaessigkeit wohnnutzungEGStrasse enumeration xplan_gml.BP_Zulaessigkeit 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.zwohn IS 'integer ZWohn integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.gfantwohnen IS 'double precision GFAntwWohnen double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.gfwohnen IS 'double precision GFWohnen double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.gfantgewerbe IS 'double precision GFAntGewerbe double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_ueberbaubaregrundstuecksflaeche.gfgewerbe IS 'double precision GFGewerbe double precision 0..1';

-- BP_GemeinbedarfsFlaeche
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN maxzahlwohnungen integer;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN fmin double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN fmax double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN bmin double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN bmax double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN tmin double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN tmax double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN gfzmin double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN gfzmax double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN gfz double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN gfz_ausn double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN gfmin double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN gfmax double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN gf double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN gf_ausn double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN bmz double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN bmz_ausn double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN bm double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN bm_ausn double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN grzmin double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN grzmax double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN grz double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN grz_ausn double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN grmin double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN grmax double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN gr double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN gr_ausn double precision;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN zmin integer;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN zmax integer;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN zzwingend integer;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN z integer;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN z_ausn integer;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN z_staffel integer;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN z_dach integer;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN zumin integer;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN zumax integer;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN zuzwingend integer;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN zu integer;
ALTER TABLE xplan_gml.bp_gemeinbedarfsflaeche ADD COLUMN zu_ausn integer;

COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.fmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.fmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.bmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.bmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.tmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.tmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.gfzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.gfzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.gfz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.gfz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.gfmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.gfmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.gf IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.gf_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.bmz IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.bmz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.bm IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.bm_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.grzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.grzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.grz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.grz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.grmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.grmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.gr IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.gr_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.zmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.zmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.zzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zzwingend integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.z IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.z_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Ausn integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.z_staffel IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Staffel integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.z_dach IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Dach integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.zumin IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.zumax IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.zuzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet integerZUzwingend 0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.zu IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu integer0..1';
COMMENT ON COLUMN xplan_gml.bp_gemeinbedarfsflaeche.zu_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu_ausn integer 0..1';

-- BP_SpielSportanlagenFlaeche
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN maxzahlwohnungen integer;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN fmin double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN fmax double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN bmin double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN bmax double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN tmin double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN tmax double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN gfzmin double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN gfzmax double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN gfz double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN gfz_ausn double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN gfmin double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN gfmax double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN gf double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN gf_ausn double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN bmz double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN bmz_ausn double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN bm double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN bm_ausn double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN grzmin double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN grzmax double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN grz double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN grz_ausn double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN grmin double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN grmax double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN gr double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN gr_ausn double precision;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN zmin integer;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN zmax integer;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN zzwingend integer;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN z integer;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN z_ausn integer;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN z_staffel integer;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN z_dach integer;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN zumin integer;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN zumax integer;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN zuzwingend integer;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN zu integer;
ALTER TABLE xplan_gml.bp_spielsportanlagenflaeche ADD COLUMN zu_ausn integer;

COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.fmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.fmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.bmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.bmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.tmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.tmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.gfzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.gfzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.gfz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.gfz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.gfmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.gfmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.gf IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.gf_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.bmz IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.bmz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.bm IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.bm_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.grzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.grzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.grz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.grz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.grmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.grmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.gr IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.gr_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.zmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.zmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.zzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zzwingend integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.z IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.z_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Ausn integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.z_staffel IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Staffel integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.z_dach IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Dach integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.zumin IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.zumax IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.zuzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet integerZUzwingend 0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.zu IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu integer0..1';
COMMENT ON COLUMN xplan_gml.bp_spielsportanlagenflaeche.zu_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu_ausn integer 0..1';


ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN maxzahlwohnungen integer;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN fmin double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN fmax double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN bmin double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN bmax double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN tmin double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN tmax double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN gfzmin double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN gfzmax double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN gfz double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN gfz_ausn double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN gfmin double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN gfmax double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN gf double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN gf_ausn double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN bmz double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN bmz_ausn double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN bm double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN bm_ausn double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN grzmin double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN grzmax double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN grz double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN grz_ausn double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN grmin double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN grmax double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN gr double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN gr_ausn double precision;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN zmin integer;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN zmax integer;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN zzwingend integer;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN z integer;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN z_ausn integer;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN z_staffel integer;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN z_dach integer;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN zumin integer;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN zumax integer;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN zuzwingend integer;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN zu integer;
ALTER TABLE xplan_gml.bp_verentsorgung ADD COLUMN zu_ausn integer; 

COMMENT ON COLUMN xplan_gml.bp_verentsorgung.fmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.fmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.bmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.bmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.tmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.tmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.gfzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.gfzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.gfz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.gfz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.gfmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.gfmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.gf IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.gf_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.bmz IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.bmz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.bm IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.bm_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.grzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.grzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.grz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.grz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.grmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.grmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.gr IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.gr_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.zmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.zmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.zzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zzwingend integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.z IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.z_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Ausn integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.z_staffel IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Staffel integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.z_dach IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Dach integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.zumin IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.zumax IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.zuzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet integerZUzwingend 0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.zu IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu integer0..1';
COMMENT ON COLUMN xplan_gml.bp_verentsorgung.zu_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu_ausn integer 0..1';

-- BP:VerkehrsflaecheBesondererZweckbestimmung
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN maxzahlwohnungen integer;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN fmin double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN fmax double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN bmin double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN bmax double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN tmin double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN tmax double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN gfzmin double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN gfzmax double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN gfz double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN gfz_ausn double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN gfmin double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN gfmax double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN gf double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN gf_ausn double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN bmz double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN bmz_ausn double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN bm double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN bm_ausn double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN grzmin double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN grzmax double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN grz double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN grz_ausn double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN grmin double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN grmax double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN gr double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN gr_ausn double precision;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN zmin integer;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN zmax integer;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN zzwingend integer;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN z integer;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN z_ausn integer;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN z_staffel integer;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN z_dach integer;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN zumin integer;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN zumax integer;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN zuzwingend integer;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN zu integer;
ALTER TABLE xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung ADD COLUMN zu_ausn integer;

COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.fmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.fmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.bmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.bmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.tmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.tmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.gfzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.gfzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.gfz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.gfz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.gfmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.gfmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.gf IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.gf_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.bmz IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.bmz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.bm IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.bm_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.grzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.grzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.grz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.grz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.grmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.grmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.gr IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.gr_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.zmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.zmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.zzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zzwingend integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.z IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.z_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Ausn integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.z_staffel IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Staffel integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.z_dach IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Dach integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.zumin IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.zumax IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.zuzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet integerZUzwingend 0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.zu IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu integer0..1';
COMMENT ON COLUMN xplan_gml.bp_verkehrsflaechebesondererzweckbestimmung.zu_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu_ausn integer 0..1';

-- BP_StrassenVerkehrsFlaeche
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN maxzahlwohnungen integer;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN fmin double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN fmax double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN bmin double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN bmax double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN tmin double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN tmax double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN gfzmin double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN gfzmax double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN gfz double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN gfz_ausn double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN gfmin double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN gfmax double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN gf double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN gf_ausn double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN bmz double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN bmz_ausn double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN bm double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN bm_ausn double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN grzmin double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN grzmax double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN grz double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN grz_ausn double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN grmin double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN grmax double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN gr double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN gr_ausn double precision;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN zmin integer;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN zmax integer;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN zzwingend integer;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN z integer;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN z_ausn integer;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN z_staffel integer;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN z_dach integer;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN zumin integer;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN zumax integer;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN zuzwingend integer;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN zu integer;
ALTER TABLE xplan_gml.bp_strassenverkehrsflaeche ADD COLUMN zu_ausn integer;

COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.fmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.fmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Fmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.bmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.bmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Bmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.tmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.tmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Tmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.gfzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.gfzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.gfz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.gfz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.gfmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.gfmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GFZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.gf IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.gf_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GF_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.bmz IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.bmz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BMZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.bm IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.bm_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet BM_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.grzmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.grzmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.grz IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.grz_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRZ_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.grmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmin double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.grmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet GRmax double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.gr IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.gr_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet GR_Ausn double precision 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.zmin IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.zmax IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.zzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet Zzwingend integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.z IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.z_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Ausn integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.z_staffel IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Staffel integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.z_dach IS 'Ableitung von Type BP_FestsetzungenBaugebiet Z_Dach integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.zumin IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmin integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.zumax IS 'Ableitung von Type BP_FestsetzungenBaugebiet ZUmax integer 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.zuzwingend IS 'Ableitung von Type BP_FestsetzungenBaugebiet integerZUzwingend 0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.zu IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu integer0..1';
COMMENT ON COLUMN xplan_gml.bp_strassenverkehrsflaeche.zu_ausn IS 'Ableitung von Type BP_FestsetzungenBaugebiet zu_ausn integer 0..1';

COMMIT;