BEGIN;
-- Fix regel id wasserwitschaft to wasserwirtschaft
UPDATE xplankonverter.mappingtable_gmlas_to_gml
SET regel = 'gmlas.zweckbestimmung::xplan_gml.xp_zweckbestimmungwasserwirtschaft AS zweckbestimmung'
WHERE regel = 'gmlas.zweckbestimmung::xplan_gml.xp_zweckbestimmungwasserwitschaft AS zweckbestimmung';

INSERT INTO
    xplankonverter.mappingtable_gmlas_to_gml (id, feature_class, o_table, o_column, o_data_type, t_table, t_column, t_data_type, codespace, complex_type, regel)
VALUES
(
    4237,
    TRUE,
    'fp_generischesobjekt',
    'ebene',
    'integer',
    'fp_generischesobjekt',
    'ebene',
    'integer',
    NULL,
    NULL,
    'gmlas.ebene AS ebene'
),
(
    4238,
    TRUE,
    'fp_generischesobjekt',
    'flaechenschluss',
    'boolean',
    'fp_generischesobjekt',
    'flaechenschluss',
    'boolean',
    NULL,
    NULL,
    'gmlas.flaechenschluss AS flaechenschluss'
),
(
    4239,
    TRUE,
    'fp_generischesobjekt',
    'gehoertzubereich_href',
    'character varying',
    'fp_generischesobjekt',
    'gehoertzubereich',
    'text',
    NULL,
    NULL,
    'CASE WHEN gmlas.gehoertzubereich_href LIKE ''#GML_%'' OR gmlas.gehoertzubereich_href LIKE ''#gml_%'' OR gmlas.gehoertzubereich_href LIKE ''#Gml_%'' THEN substring(gmlas.gehoertzubereich_href, 6) ELSE gmlas.gehoertzubereich_href END AS gehoertzubereich'
),
(
    4240,
    TRUE,
    'fp_generischesobjekt',
    'gesetzlichegrundlage',
    'character varying',
    'fp_generischesobjekt',
    'gesetzlichegrundlage',
    'xp_gesetzlichegrundlage',
    'gesetzlichegrundlage_codespace',
    NULL,
    '(gmlas.gesetzlichegrundlage_codespace,gmlas.gesetzlichegrundlage,NULL)::xplan_gml.xp_gesetzlichegrundlage AS gesetzlichegrundlage'
),
(
    4241,
    TRUE,
    'fp_generischesobjekt',
    'gliederung1',
    'character varying',
    'fp_generischesobjekt',
    'gliederung1',
    'character varying',
    NULL,
    NULL,
    'gmlas.gliederung1 AS gliederung1'
),
(
    4242,
    TRUE,
    'fp_generischesobjekt',
    'gliederung2',
    'character varying',
    'fp_generischesobjekt',
    'gliederung2',
    'character varying',
    NULL,
    NULL,
    'gmlas.gliederung2 AS gliederung2'
),
(
    4243,
    TRUE,
    'fp_generischesobjekt',
    'id',
    'character varying',
    'fp_generischesobjekt',
    'gml_id',
    'uuid',
    NULL,
    NULL,
    'CASE WHEN gmlas.id LIKE ''GML_%'' OR gmlas.id LIKE ''gml_%'' OR gmlas.id LIKE ''Gml_%'' THEN substring(gmlas.id, 5)::uuid ELSE gmlas.id::uuid END AS gml_id'
),
(
    4244,
    TRUE,
    'fp_generischesobjekt',
    'nordwinkel',
    'double precision',
    'fp_generischesobjekt',
    'nordwinkel',
    'double precision',
    NULL,
    NULL,
    'gmlas.nordwinkel AS nordwinkel'
),
(
    4245,
    TRUE,
    'fp_generischesobjekt',
    'position',
    'geometry',
    'fp_generischesobjekt',
    'position',
    'geometry',
    NULL,
    NULL,
    'gmlas.position AS position'
),
(
    4246,
    TRUE,
    'fp_generischesobjekt',
    'rechtscharakter',
    'character varying',
    'fp_generischesobjekt',
    'rechtscharakter',
    'fp_rechtscharakter',
    NULL,
    NULL,
    'gmlas.rechtscharakter::xplan_gml.fp_rechtscharakter AS rechtscharakter'
),
(
    4247,
    TRUE,
    'fp_generischesobjekt',
    'rechtsstand',
    'character varying',
    'fp_generischesobjekt',
    'rechtsstand',
    'xp_rechtsstand',
    NULL,
    NULL,
    'gmlas.rechtsstand::xplan_gml.xp_rechtsstand AS rechtsstand'
),
(
    4248,
    TRUE,
    'fp_generischesobjekt',
    'spezifischepraegung',
    'character varying',
    'fp_generischesobjekt',
    'spezifischepraegung',
    'fp_spezifischepraegungtypen',
    'spezifischepraegung_codespace',
    NULL,
    '(gmlas.spezifischepraegung_codespace,gmlas.spezifischepraegung,NULL)::xplan_gml.fp_spezifischepraegungtypen AS spezifischepraegung'
),
(
    4249,
    TRUE,
    'fp_generischesobjekt',
    'text',
    'character varying',
    'fp_generischesobjekt',
    'text',
    'character varying',
    NULL,
    NULL,
    'gmlas.text AS text'
),
(
    4250,
    TRUE,
    'fp_generischesobjekt',
    'uuid',
    'character varying',
    'fp_generischesobjekt',
    'uuid',
    'character varying',
    NULL,
    NULL,
    'gmlas.uuid AS uuid'
),
(
    4251,
    TRUE,
    'fp_generischesobjekt',
    'zweckbestimmung',
    'ARRAY character varying',
    'fp_generischesobjekt',
    'zweckbestimmung',
    'fp_zweckbestimmunggenerischeobjekte',
    'fp_zweckbestimmungenerischeobjekte_spezifischepraegung_codespace',
    NULL,'(gmlas.fp_zweckbestimmungenerischeobjekte_spezifischepraegung_codespace,gmlas.fp_zweckbestimmungenerischeobjekte_spezifischepraegung,NULL)::xplan_gml.fp_zweckbestimmunggenerischeobjekte AS zweckbestimmung'
),
(
    4252,
    TRUE,
    'fp_generischesobjekt_externereferenz_externereferenz',
    'ogc_fid',
    'integer',
    'fp_generischesobjekt',
    'ogc_fid',
    'xp_spezexternereferenz',
    NULL,
    'xp_spezexternereferenz',
    'gmlas.ogc_fid AS ogc_fid'
),
(
    4253,
    TRUE,
    'fp_generischesobjekt_hoehenangabe_hoehenangabe',
    'ogc_fid',
    'integer',
    'fp_generischesobjekt',
    'hoehenangabe',
    'xp_hoehenangabe',
    NULL,
    'xp_hoehenangabe[]','ARRAY[gmlas.xp_hoehenangabe_abweichenderhoehenbezug,gmlas.xp_hoehenangabe_hoehenbezug::xplan_gml.xp_arthoehenbezung,gmlas.xp_hoehenangabe_bezugspunkt::xplan_gml.xp_arthoehenbezugspunkt,gmlas.xp_hoehenangabe_hmin,gmlas.xp_hoehenangabe_hmax,gmlas.xp_hoehenangabe_hzwingend,gmlas.xp_hoehenangabe_h,gmlas.xp_hoehenangabe_abweichenderbezugspunkt]::xplan_gml.xp_hoehenangabe[] AS hoehenangabe'
),
(
    4254,
    TRUE,
    'fp_generischesobjekt_refbegruendunginhalt',
    'href',
    'character varying',
    'fp_generischesobjekt',
    'refbegruendunginhalt',
    'text',
    NULL,
    NULL,
    'gmlas.href AS refbegruendunginhalt'
),
(
    4255,
    TRUE,
    'fp_generischesobjekt_reftextinhalt',
    'href',
    'character varying',
    'fp_generischesobjekt',
    'reftextinhalt',
    'text',
    NULL,
    NULL,
    'gmlas.href AS reftextinhalt'
),
(
    4256,
    TRUE,
    'fp_generischesobjekt_wirdausgeglichendurchflaeche',
    'href',
    'character varying',
    'fp_generischesobjekt',
    'wirdausgeglichendurchflaeche',
    'text',
    NULL,
    NULL,
    'gmlas.href AS wirdausgeglichendurchflaeche'
),
(
    4257,
    TRUE,
    'fp_generischesobjekt_wirdausgeglichendurchspe',
    'href',
    'character varying',
    'fp_generischesobjekt',
    'wirddargestelltdurch',
    'text',
    NULL,
    NULL,
    'gmlas.href AS wirddargestelltdurch'
),
(
    4258,
    TRUE,
    'fp_generischesobjekt_wirddargestelltdurch',
    'href',
    'character varying',
    'fp_generischesobjekt',
    'wirddargestelltdurch',
    'text',
    NULL,
    NULL,
    'gmlas.href AS wirddargestelltdurch'
);

INSERT INTO
    xplankonverter.mappingtable_gmlas_to_gml (id, feature_class, o_table, o_column, o_data_type, t_table, t_column, t_data_type, codespace, complex_type, regel)
VALUES
(
    4259,
    TRUE,
    'bp_generischesobjekt',
    'ebene',
    'integer',
    'bp_generischesobjekt',
    'ebene',
    'integer',
    NULL,
    NULL,
    'gmlas.ebene AS ebene'
),
(
    4260,
    TRUE,
    'bp_generischesobjekt',
    'flaechenschluss',
    'boolean',
    'bp_generischesobjekt',
    'flaechenschluss',
    'boolean',
    NULL,
    NULL,
    'gmlas.flaechenschluss AS flaechenschluss'
),
(
    4261,
    TRUE,
    'bp_generischesobjekt',
    'flussrichtung',
    'boolean',
    'bp_generischesobjekt',
    'flussrichtung',
    'boolean',
    NULL,
    NULL,
    'gmlas.flussrichtung AS flussrichtung'
),
(
    4262,
    TRUE,
    'bp_generischesobjekt',
    'gehoertzubereich_href',
    'character varying',
    'bp_generischesobjekt',
    'gehoertzubereich',
    'text',
    NULL,
    NULL,
    'CASE WHEN gmlas.gehoertzubereich_href LIKE ''#GML_%'' OR gmlas.gehoertzubereich_href LIKE ''#gml_%'' OR gmlas.gehoertzubereich_href LIKE ''#Gml_%'' THEN substring(gmlas.gehoertzubereich_href, 6) ELSE gmlas.gehoertzubereich_href END AS gehoertzubereich'
),
(
    4263,
    TRUE,
    'bp_generischesobjekt',
    'gesetzlichegrundlage',
    'character varying',
    'bp_generischesobjekt',
    'gesetzlichegrundlage',
    'xp_gesetzlichegrundlage',
    'gesetzlichegrundlage_codespace',
    NULL,
    '(gmlas.gesetzlichegrundlage_codespace,gmlas.gesetzlichegrundlage,NULL)::xplan_gml.xp_gesetzlichegrundlage AS gesetzlichegrundlage'
),
(
    4264,
    TRUE,
    'bp_generischesobjekt',
    'gliederung1',
    'character varying',
    'bp_generischesobjekt',
    'gliederung1',
    'character varying',
    NULL,
    NULL,
    'gmlas.gliederung1 AS gliederung1'
),
(
    4265,
    TRUE,
    'bp_generischesobjekt',
    'gliederung2',
    'character varying',
    'bp_generischesobjekt',
    'gliederung2',
    'character varying',
    NULL,
    NULL,
    'gmlas.gliederung2 AS gliederung2'
),
(
    4266,
    TRUE,
    'bp_generischesobjekt',
    'id',
    'character varying',
    'bp_generischesobjekt',
    'gml_id',
    'uuid',
    NULL,
    NULL,
    'CASE WHEN gmlas.id LIKE ''GML_%'' OR gmlas.id LIKE ''gml_%'' OR gmlas.id LIKE ''Gml_%'' THEN substring(gmlas.id, 5)::uuid ELSE gmlas.id::uuid END AS gml_id'
),
(
    4267,
    TRUE,
    'bp_generischesobjekt',
    'nordwinkel',
    'double precision',
    'bp_generischesobjekt',
    'nordwinkel',
    'double precision',
    NULL,
    NULL,
    'gmlas.nordwinkel AS nordwinkel'
),
(
    4268,
    TRUE,
    'bp_generischesobjekt',
    'position',
    'geometry',
    'bp_generischesobjekt',
    'position',
    'geometry',
    NULL,
    NULL,
    'gmlas.position AS position'
),
(
    4269,
    TRUE,
    'bp_generischesobjekt',
    'rechtscharakter',
    'character varying',
    'bp_generischesobjekt',
    'rechtscharakter',
    'bp_rechtscharakter',
    NULL,
    NULL,
    'gmlas.rechtscharakter::xplan_gml.bp_rechtscharakter AS rechtscharakter'
),
(
    4270,
    TRUE,
    'bp_generischesobjekt',
    'rechtsstand',
    'character varying',
    'bp_generischesobjekt',
    'rechtsstand',
    'xp_rechtsstand',
    NULL,
    NULL,
    'gmlas.rechtsstand::xplan_gml.xp_rechtsstand AS rechtsstand'
),
(
    4271,
    TRUE,
    'bp_generischesobjekt',
    'text',
    'character varying',
    'bp_generischesobjekt',
    'text',
    'character varying',
    NULL,
    NULL,
    'gmlas.text AS text'
),
(
    4272,
    TRUE,
    'bp_generischesobjekt',
    'uuid',
    'character varying',
    'bp_generischesobjekt',
    'uuid',
    'character varying',
    NULL,
    NULL,
    'gmlas.uuid AS uuid'
),
(
    4273,
    TRUE,
    'bp_generischesobjekt',
    'zweckbestimmung',
    'ARRAY character varying',
    'bp_generischesobjekt',
    'zweckbestimmung',
    'bp_zweckbestimmunggenerischeobjekte',
    'bp_zweckbestimmungenerischeobjekte_spezifischepraegung_codespace',
    NULL,'(gmlas.bp_zweckbestimmungenerischeobjekte_spezifischepraegung_codespace,gmlas.bp_zweckbestimmungenerischeobjekte_spezifischepraegung,NULL)::xplan_gml.bp_zweckbestimmunggenerischeobjekte AS zweckbestimmung'
),
(
    4274,
    TRUE,
    'bp_generischesobjekt_externereferenz_externereferenz',
    'ogc_fid',
    'integer',
    'bp_generischesobjekt',
    'ogc_fid',
    'xp_spezexternereferenz',
    NULL,
    'xp_spezexternereferenz',
    'gmlas.ogc_fid AS ogc_fid'
),
(
    4275,
    TRUE,
    'bp_generischesobjekt_hoehenangabe_hoehenangabe',
    'ogc_fid',
    'integer',
    'bp_generischesobjekt',
    'hoehenangabe',
    'xp_hoehenangabe',
    NULL,
    'xp_hoehenangabe[]','ARRAY[gmlas.xp_hoehenangabe_abweichenderhoehenbezug,gmlas.xp_hoehenangabe_hoehenbezug::xplan_gml.xp_arthoehenbezung,gmlas.xp_hoehenangabe_bezugspunkt::xplan_gml.xp_arthoehenbezugspunkt,gmlas.xp_hoehenangabe_hmin,gmlas.xp_hoehenangabe_hmax,gmlas.xp_hoehenangabe_hzwingend,gmlas.xp_hoehenangabe_h,gmlas.xp_hoehenangabe_abweichenderbezugspunkt]::xplan_gml.xp_hoehenangabe[] AS hoehenangabe'
),
(
    4276,
    TRUE,
    'bp_generischesobjekt_refbegruendunginhalt',
    'href',
    'character varying',
    'bp_generischesobjekt',
    'refbegruendunginhalt',
    'text',
    NULL,
    NULL,
    'gmlas.href AS refbegruendunginhalt'
),
(
    4277,
    TRUE,
    'bp_generischesobjekt_reftextinhalt',
    'href',
    'character varying',
    'bp_generischesobjekt',
    'reftextinhalt',
    'text',
    NULL,
    NULL,
    'gmlas.href AS reftextinhalt'
),
(
    4278,
    TRUE,
    'bp_hoehenmass_wirdausgeglichendurchabe',
    'href',
    'character varying',
    'bp_generischesobjekt',
    'wirdausgeglichendurchabe',
    'text',
    NULL,
    NULL,
    'gmlas.href AS wirdausgeglichendurchabe'
),
(
    4279,
    TRUE,
    'bp_generischesobjekt_wirdausgeglichendurchflaeche',
    'href',
    'character varying',
    'bp_generischesobjekt',
    'wirdausgeglichendurchflaeche',
    'text',
    NULL,
    NULL,
    
    'gmlas.href AS wirdausgeglichendurchflaeche'
),
(
    4280,
    TRUE,
    'bp_hoehenmass_wirdausgeglichendurchmassnahme',
    'href',
    'character varying',
    'bp_generischesobjekt',
    'wirdausgeglichendurchmassnahme',
    'text',
    NULL,
    NULL,
    'gmlas.href AS wirdausgeglichendurchmassnahme'
),
(
    4281,
    TRUE,
    'bp_hoehenmass_wirdausgeglichendurchspeflaeche',
    'href',
    'character varying',
    'bp_generischesobjekt',
    'wirdausgeglichendurchspeflaeche',
    'text',
    NULL,
    NULL,
    'gmlas.href AS wirdausgeglichendurchspeflaeche'
),
(
    4282,
    TRUE,
    'bp_hoehenmass_wirdausgeglichendurchspemassnahme',
    'href',
    'character varying',
    'bp_generischesobjekt',
    'wirdausgeglichendurchspemassnahme',
    'text',
    NULL,
    NULL,
    'gmlas.href AS wirdausgeglichendurchspemassnahme'
),
(
    4283,
    TRUE,
    'bp_generischesobjekt_wirddargestelltdurch',
    'href',
    'character varying',
    'bp_generischesobjekt',
    'wirddargestelltdurch',
    'text',
    NULL,
    NULL,
    'gmlas.href AS wirddargestelltdurch'
);

INSERT INTO
    xplankonverter.mappingtable_gmlas_to_gml (id, feature_class, o_table, o_column, o_data_type, t_table, t_column, t_data_type, codespace, complex_type, regel)
VALUES
(
    4284,
    TRUE,
    'lp_generischesobjekt',
    'ebene',
    'integer',
    'lp_generischesobjekt',
    'ebene',
    'integer',
    NULL,
    NULL,
    'gmlas.ebene AS ebene'
),
(
    4285,
    TRUE,
    'lp_generischesobjekt',
    'flussrichtung',
    'boolean',
    'lp_generischesobjekt',
    'flussrichtung',
    'boolean',
    NULL,
    NULL,
    'gmlas.flussrichtung AS flussrichtung'
),
(
    4286,
    TRUE,
    'lp_generischesobjekt',
    'gehoertzubereich_href',
    'character varying',
    'lp_generischesobjekt',
    'gehoertzubereich',
    'text',
    NULL,
    NULL,
    'CASE WHEN gmlas.gehoertzubereich_href LIKE ''#GML_%'' OR gmlas.gehoertzubereich_href LIKE ''#gml_%'' OR gmlas.gehoertzubereich_href LIKE ''#Gml_%'' THEN substring(gmlas.gehoertzubereich_href, 6) ELSE gmlas.gehoertzubereich_href END AS gehoertzubereich'
),
(
    4287,
    TRUE,
    'lp_generischesobjekt',
    'gesetzlichegrundlage',
    'character varying',
    'lp_generischesobjekt',
    'gesetzlichegrundlage',
    'xp_gesetzlichegrundlage',
    'gesetzlichegrundlage_codespace',
    NULL,
    '(gmlas.gesetzlichegrundlage_codespace,gmlas.gesetzlichegrundlage,NULL)::xplan_gml.xp_gesetzlichegrundlage AS gesetzlichegrundlage'
),
(
    4288,
    TRUE,
    'lp_generischesobjekt',
    'gliederung1',
    'character varying',
    'lp_generischesobjekt',
    'gliederung1',
    'character varying',
    NULL,
    NULL,
    'gmlas.gliederung1 AS gliederung1'
),
(
    4289,
    TRUE,
    'lp_generischesobjekt',
    'gliederung2',
    'character varying',
    'lp_generischesobjekt',
    'gliederung2',
    'character varying',
    NULL,
    NULL,
    'gmlas.gliederung2 AS gliederung2'
),
(
    4290,
    TRUE,
    'lp_generischesobjekt',
    'id',
    'character varying',
    'lp_generischesobjekt',
    'gml_id',
    'uuid',
    NULL,
    NULL,
    'CASE WHEN gmlas.id LIKE ''GML_%'' OR gmlas.id LIKE ''gml_%'' OR gmlas.id LIKE ''Gml_%'' THEN substring(gmlas.id, 5)::uuid ELSE gmlas.id::uuid END AS gml_id'
),
(
    4291,
    TRUE,
    'lp_generischesobjekt',
    'konkretisierung',
    'character varying',
    'lp_generischesobjekt',
    'konkretisierung',
    NULL,
    NULL,
    NULL,
    NULL
),
(
    4292,
    TRUE,
    'lp_generischesobjekt',
    'nordwinkel',
    'double precision',
    'lp_generischesobjekt',
    'nordwinkel',
    'double precision',
    NULL,
    NULL,
    'gmlas.nordwinkel AS nordwinkel'
),
(
    4293,
    TRUE,
    'lp_generischesobjekt',
    'position',
    'geometry',
    'lp_generischesobjekt',
    'position',
    'geometry',
    NULL,
    NULL,
    'gmlas.position AS position'
),
(
    4294,
    TRUE,
    'lp_generischesobjekt',
    'rechtscharakter',
    'character varying',
    'lp_generischesobjekt',
    'rechtscharakter',
    'lp_rechtscharakter',
    NULL,
    NULL,
    'gmlas.rechtscharakter::xplan_gml.lp_rechtscharakter AS rechtscharakter'
),
(
    4295,
    TRUE,
    'lp_generischesobjekt',
    'rechtsstand',
    'character varying',
    'lp_generischesobjekt',
    'rechtsstand',
    'xp_rechtsstand',
    NULL,
    NULL,
    'gmlas.rechtsstand::xplan_gml.xp_rechtsstand AS rechtsstand'
),
(
    4296,
    TRUE,
    'lp_generischesobjekt',
    'text',
    'character varying',
    'lp_generischesobjekt',
    'text',
    'character varying',
    NULL,
    NULL,
    'gmlas.text AS text'
),
(
    4297,
    TRUE,
    'lp_generischesobjekt',
    'uuid',
    'character varying',
    'lp_generischesobjekt',
    'uuid',
    'character varying',
    NULL,
    NULL,
    'gmlas.uuid AS uuid'
),
(
    4298,
    TRUE,
    'lp_generischesobjekt',
    'zweckbestimmung',
    'ARRAY character varying',
    'lp_generischesobjekt',
    'zweckbestimmung',
    'lp_zweckbestimmunggenerischeobjekte',
    'lp_zweckbestimmungenerischeobjekte_spezifischepraegung_codespace',
    NULL,'(gmlas.lp_zweckbestimmungenerischeobjekte_spezifischepraegung_codespace,gmlas.lp_zweckbestimmungenerischeobjekte_spezifischepraegung,NULL)::xplan_gml.lp_zweckbestimmunggenerischeobjekte AS zweckbestimmung'
),
(
    4299,
    TRUE,
    'lp_generischesobjekt_externereferenz_externereferenz',
    'ogc_fid',
    'integer',
    'lp_generischesobjekt',
    'ogc_fid',
    'xp_spezexternereferenz',
    NULL,
    'xp_spezexternereferenz',
    'gmlas.ogc_fid AS ogc_fid'
),
(
    4300,
    TRUE,
    'lp_generischesobjekt_hoehenangabe_hoehenangabe',
    'ogc_fid',
    'integer',
    'lp_generischesobjekt',
    'hoehenangabe',
    'xp_hoehenangabe',
    NULL,
    'xp_hoehenangabe[]','ARRAY[gmlas.xp_hoehenangabe_abweichenderhoehenbezug,gmlas.xp_hoehenangabe_hoehenbezug::xplan_gml.xp_arthoehenbezung,gmlas.xp_hoehenangabe_bezugspunkt::xplan_gml.xp_arthoehenbezugspunkt,gmlas.xp_hoehenangabe_hmin,gmlas.xp_hoehenangabe_hmax,gmlas.xp_hoehenangabe_hzwingend,gmlas.xp_hoehenangabe_h,gmlas.xp_hoehenangabe_abweichenderbezugspunkt]::xplan_gml.xp_hoehenangabe[] AS hoehenangabe'
),
(
    4301,
    TRUE,
    'lp_generischesobjekt_refbegruendunginhalt',
    'href',
    'character varying',
    'lp_generischesobjekt',
    'refbegruendunginhalt',
    'text',
    NULL,
    NULL,
    'gmlas.href AS refbegruendunginhalt'
),
(
    4302,
    TRUE,
    'lp_generischesobjekt_reftextinhalt',
    'href',
    'character varying',
    'lp_generischesobjekt',
    'reftextinhalt',
    'text',
    NULL,
    NULL,
    'gmlas.href AS reftextinhalt'
),
(
    4303,
    TRUE,
    'lp_generischesobjekt_wirddargestelltdurch',
    'href',
    'character varying',
    'lp_generischesobjekt',
    'wirddargestelltdurch',
    'text',
    NULL,
    NULL,
    'gmlas.href AS wirddargestelltdurch'
);


INSERT INTO
    xplankonverter.mappingtable_gmlas_to_gml (id, feature_class, o_table, o_column, o_data_type, t_table, t_column, t_data_type, codespace, complex_type, regel)
VALUES
(
    4304,
    TRUE,
    'rp_generischesobjekt',
    'bedeutsamkeit',
    'ARRAY character varying',
    'rp_generischesobjekt',
    'bedeutsamkeit',
    'rp_bedeutsamkeit[]',
    NULL,
    NULL,
    'gmlas.bedeutsamkeit::xplan_gml.rp_bedeutsamkeit[] AS bedeutsamkeit'
),
(
    4305,
    TRUE,
    'rp_generischesobjekt',
    'ebene',
    'integer',
    'rp_generischesobjekt',
    'ebene',
    'integer',
    NULL,
    NULL,
    'gmlas.ebene AS ebene'
),
(
    4306,
    TRUE,
    'rp_generischesobjekt',
    'flaechenschluss',
    'boolean',
    'rp_generischesobjekt',
    'flaechenschluss',
    'boolean',
    NULL,
    NULL,
    'gmlas.flaechenschluss AS flaechenschluss'
),
(
    4307,
    TRUE,
    'rp_generischesobjekt',
    'flussrichtung',
    'boolean',
    'rp_generischesobjekt',
    'flussrichtung',
    'boolean',
    NULL,
    NULL,
    'gmlas.flussrichtung AS flussrichtung'
),
(
    4308,
    TRUE,
    'rp_generischesobjekt',
    'gebietstyp',
    'ARRAY character varying',
    'rp_generischesobjekt',
    'gebietstyp',
    'rp_gebietstyp[]',
    NULL,
    NULL,
    'gmlas.gebietstyp::xplan_gml.rp_gebietstyp[] AS gebietstyp'
),
(
    4309,
    TRUE,
    'rp_generischesobjekt',
    'gehoertzubereich_href',
    'character varying',
    'rp_generischesobjekt',
    'gehoertzubereich',
    'text',
    NULL,
    NULL,
    'CASE WHEN gmlas.gehoertzubereich_href LIKE ''#GML_%'' OR gmlas.gehoertzubereich_href LIKE ''#gml_%'' OR gmlas.gehoertzubereich_href LIKE ''#Gml_%'' THEN substring(gmlas.gehoertzubereich_href, 6) ELSE gmlas.gehoertzubereich_href END AS gehoertzubereich'
),
(
    4310,
    TRUE,
    'rp_generischesobjekt',
    'gesetzlichegrundlage',
    'character varying',
    'rp_generischesobjekt',
    'gesetzlichegrundlage',
    'xp_gesetzlichegrundlage',
    'gesetzlichegrundlage_codespace',
    NULL,
    '(gmlas.gesetzlichegrundlage_codespace,gmlas.gesetzlichegrundlage,NULL)::xplan_gml.xp_gesetzlichegrundlage AS gesetzlichegrundlage'
),
(
    4311,
    TRUE,
    'rp_generischesobjekt',
    'gliederung1',
    'character varying',
    'rp_generischesobjekt',
    'gliederung1',
    'character varying',
    NULL,
    NULL,
    'gmlas.gliederung1 AS gliederung1'
),
(
    4312,
    TRUE,
    'rp_generischesobjekt',
    'gliederung2',
    'character varying',
    'rp_generischesobjekt',
    'gliederung2',
    'character varying',
    NULL,
    NULL,
    'gmlas.gliederung2 AS gliederung2'
),
(
    4313,
    TRUE,
    'rp_generischesobjekt',
    'id',
    'character varying',
    'rp_generischesobjekt',
    'gml_id',
    'uuid',
    NULL,
    NULL,
    'CASE WHEN gmlas.id LIKE ''GML_%'' OR gmlas.id LIKE ''gml_%'' OR gmlas.id LIKE ''Gml_%'' THEN substring(gmlas.id, 5)::uuid ELSE gmlas.id::uuid END AS gml_id'
),
(
    4314,
    TRUE,
    'rp_generischesobjekt',
    'istzweckbindung',
    'boolean',
    'rp_generischesobjekt',
    'istzweckbindung',
    'boolean',
    NULL,
    NULL,
    'gmlas.istzweckbindung AS istzweckbindung'
),
(
    4315,
    TRUE,
    'rp_generischesobjekt',
    'konkretisierung',
    'character varying',
    'rp_generischesobjekt',
    'konkretisierung',
    'character varying',
    NULL,
    NULL,
    'gmlas.konkretisierung AS konkretisierung'
),
(
    4316,
    TRUE,
    'rp_generischesobjekt',
    'kuestenmeer',
    'boolean',
    'rp_generischesobjekt',
    'kuestenmeer',
    'boolean',
    NULL,
    NULL,
    'gmlas.kuestenmeer AS kuestenmeer'
),
(
    4317,
    TRUE,
    'rp_generischesobjekt',
    'position',
    'geometry',
    'rp_generischesobjekt',
    'position',
    'geometry',
    NULL,
    NULL,
    'gmlas.position AS position'
),
(
    4318,
    TRUE,
    'rp_generischesobjekt',
    'rechtscharakter',
    'character varying',
    'rp_generischesobjekt',
    'rechtscharakter',
    'rp_rechtscharakter',
    NULL,
    NULL,
    'gmlas.rechtscharakter::xplan_gml.rp_rechtscharakter AS rechtscharakter'
),
(
    4319,
    TRUE,
    'rp_generischesobjekt',
    'rechtsstand',
    'character varying',
    'rp_generischesobjekt',
    'rechtsstand',
    'xp_rechtsstand',
    NULL,
    NULL,
    'gmlas.rechtsstand::xplan_gml.xp_rechtsstand AS rechtsstand'
),
(
    4320,
    TRUE,
    'rp_generischesobjekt',
    'text',
    'character varying',
    'rp_generischesobjekt',
    'text',
    'character varying',
    NULL,
    NULL,
    'gmlas.text AS text'
),
(
    4321,
    TRUE,
    'rp_generischesobjekt',
    'typ',
    'ARRAY character varying',
    'rp_generischesobjekt',
    'typ',
    'xp_grenzetypen[]',
    NULL,
    NULL,
    'gmlastyp::xplan_gml.xp_grenzetypen[] AS typ'
),
(
    4322,
    TRUE,
    'rp_generischesobjekt',
    'uuid',
    'character varying',
    'rp_generischesobjekt',
    'uuid',
    'character varying',
    NULL,
    NULL,
    'gmlas.uuid AS uuid'
),
(
    4323,
    TRUE,
    'rp_generischesobjekt_externereferenz_externereferenz',
    'ogc_fid',
    'integer',
    'rp_generischesobjekt',
    'ogc_fid',
    'xp_spezexternereferenz',
    NULL,
    'xp_spezexternereferenz',
    'gmlas.ogc_fid AS ogc_fid'
),
(
    4324,
    TRUE,
    'rp_generischesobjekt_hoehenangabe_hoehenangabe',
    'ogc_fid',
    'integer',
    'rp_generischesobjekt',
    'hoehenangabe',
    'xp_hoehenangabe',
    NULL,
    'xp_hoehenangabe[]','ARRAY[gmlas.xp_hoehenangabe_abweichenderhoehenbezug,gmlas.xp_hoehenangabe_hoehenbezug::xplan_gml.xp_arthoehenbezung,gmlas.xp_hoehenangabe_bezugspunkt::xplan_gml.xp_arthoehenbezugspunkt,gmlas.xp_hoehenangabe_hmin,gmlas.xp_hoehenangabe_hmax,gmlas.xp_hoehenangabe_hzwingend,gmlas.xp_hoehenangabe_h,gmlas.xp_hoehenangabe_abweichenderbezugspunkt]::xplan_gml.xp_hoehenangabe[] AS hoehenangabe'
),
(
    4325,
    TRUE,
    'rp_generischesobjekt_refbegruendunginhalt',
    'href',
    'character varying',
    'rp_generischesobjekt',
    'refbegruendunginhalt',
    'text',
    NULL,
    NULL,
    'gmlas.href AS refbegruendunginhalt'
),
(
    4326,
    TRUE,
    'rp_generischesobjekt_reftextinhalt',
    'href',
    'character varying',
    'rp_generischesobjekt',
    'reftextinhalt',
    'text',
    NULL,
    NULL,
    'gmlas.href AS reftextinhalt'
),
(
    4327,
    TRUE,
    'rp_generischesobjekt_wirddargestelltdurch',
    'href',
    'character varying',
    'rp_generischesobjekt',
    'wirddargestelltdurch',
    'text',
    NULL,
    NULL,
    'gmlas.href AS wirddargestelltdurch'
);
COMMIT;