BEGIN;
TRUNCATE xplan_gml.enum_rp_abfallentsorgungtypen;
INSERT INTO xplan_gml.enum_rp_abfallentsorgungtypen (wert, beschreibung) VALUES (1000, 'BeseitigungEntsorgung');
INSERT INTO xplan_gml.enum_rp_abfallentsorgungtypen (wert, beschreibung) VALUES (1100, 'Abfallbeseitigungsanlage');
INSERT INTO xplan_gml.enum_rp_abfallentsorgungtypen (wert, beschreibung) VALUES (1101, 'ZentraleAbfallbeseitigungsanlage');
INSERT INTO xplan_gml.enum_rp_abfallentsorgungtypen (wert, beschreibung) VALUES (1200, 'Deponie');
INSERT INTO xplan_gml.enum_rp_abfallentsorgungtypen (wert, beschreibung) VALUES (1300, 'Untertageeinlagerung');
INSERT INTO xplan_gml.enum_rp_abfallentsorgungtypen (wert, beschreibung) VALUES (1400, 'Behandlung');
INSERT INTO xplan_gml.enum_rp_abfallentsorgungtypen (wert, beschreibung) VALUES (1500, 'Kompostierung');
INSERT INTO xplan_gml.enum_rp_abfallentsorgungtypen (wert, beschreibung) VALUES (1600, 'Verbrennung');
INSERT INTO xplan_gml.enum_rp_abfallentsorgungtypen (wert, beschreibung) VALUES (1700, 'Umladestation');
INSERT INTO xplan_gml.enum_rp_abfallentsorgungtypen (wert, beschreibung) VALUES (1800, 'Standortsicherung');
INSERT INTO xplan_gml.enum_rp_abfallentsorgungtypen (wert, beschreibung) VALUES (9999, 'SonstigeAbfallentsorgung');

TRUNCATE xplan_gml.enum_rp_abfalltypen;
INSERT INTO xplan_gml.enum_rp_abfalltypen (wert, beschreibung) VALUES (1000, 'Siedlungsabfall');
INSERT INTO xplan_gml.enum_rp_abfalltypen (wert, beschreibung) VALUES (2000, 'Mineralstoffabfall');
INSERT INTO xplan_gml.enum_rp_abfalltypen (wert, beschreibung) VALUES (3000, 'Industrieabfall');
INSERT INTO xplan_gml.enum_rp_abfalltypen (wert, beschreibung) VALUES (4000, 'Sonderabfall');
INSERT INTO xplan_gml.enum_rp_abfalltypen (wert, beschreibung) VALUES (5000, 'RadioaktiverAbfall');
INSERT INTO xplan_gml.enum_rp_abfalltypen (wert, beschreibung) VALUES (9999, 'SonstigerAbfall');

TRUNCATE xplan_gml.enum_rp_abwassertypen;
INSERT INTO xplan_gml.enum_rp_abwassertypen (wert, beschreibung) VALUES (1000, 'Klaeranlage');
INSERT INTO xplan_gml.enum_rp_abwassertypen (wert, beschreibung) VALUES (1001, 'ZentraleKlaeranlage');
INSERT INTO xplan_gml.enum_rp_abwassertypen (wert, beschreibung) VALUES (1002, 'Grossklaerwerk');
INSERT INTO xplan_gml.enum_rp_abwassertypen (wert, beschreibung) VALUES (2000, 'Hauptwasserableitung');
INSERT INTO xplan_gml.enum_rp_abwassertypen (wert, beschreibung) VALUES (3000, 'Abwasserverwertungsflaeche');
INSERT INTO xplan_gml.enum_rp_abwassertypen (wert, beschreibung) VALUES (4000, 'Abwasserbehandlungsanlage');
INSERT INTO xplan_gml.enum_rp_abwassertypen (wert, beschreibung) VALUES (9999, 'SonstigeAbwasserinfrastruktur');

TRUNCATE xplan_gml.enum_rp_achsentypen;
INSERT INTO xplan_gml.enum_rp_achsentypen (wert, beschreibung) VALUES (1000, 'Achse');
INSERT INTO xplan_gml.enum_rp_achsentypen (wert, beschreibung) VALUES (2000, 'Siedlungsachse');
INSERT INTO xplan_gml.enum_rp_achsentypen (wert, beschreibung) VALUES (3000, 'Entwicklungsachse');
INSERT INTO xplan_gml.enum_rp_achsentypen (wert, beschreibung) VALUES (3001, 'Landesentwicklungsachse');
INSERT INTO xplan_gml.enum_rp_achsentypen (wert, beschreibung) VALUES (3002, 'Verbindungsachse');
INSERT INTO xplan_gml.enum_rp_achsentypen (wert, beschreibung) VALUES (3003, 'Entwicklungskorridor');
INSERT INTO xplan_gml.enum_rp_achsentypen (wert, beschreibung) VALUES (4000, 'AbgrenzungEntwicklungsEntlastungsorte');
INSERT INTO xplan_gml.enum_rp_achsentypen (wert, beschreibung) VALUES (5000, 'Achsengrundrichtung');
INSERT INTO xplan_gml.enum_rp_achsentypen (wert, beschreibung) VALUES (6000, 'AuessererAchsenSchwerpunkt');
INSERT INTO xplan_gml.enum_rp_achsentypen (wert, beschreibung) VALUES (9999, 'SonstigeAchse');

TRUNCATE xplan_gml.enum_rp_art;
INSERT INTO xplan_gml.enum_rp_art (wert, beschreibung) VALUES (1000, 'Regionalplan');
INSERT INTO xplan_gml.enum_rp_art (wert, beschreibung) VALUES (2000, 'SachlicherTeilplanRegionalebene');
INSERT INTO xplan_gml.enum_rp_art (wert, beschreibung) VALUES (2001, 'SachlicherTeilplanLandesebene');
INSERT INTO xplan_gml.enum_rp_art (wert, beschreibung) VALUES (3000, 'Braunkohlenplan');
INSERT INTO xplan_gml.enum_rp_art (wert, beschreibung) VALUES (4000, 'LandesweiterRaumordnungsplan');
INSERT INTO xplan_gml.enum_rp_art (wert, beschreibung) VALUES (5000, 'StandortkonzeptBund');
INSERT INTO xplan_gml.enum_rp_art (wert, beschreibung) VALUES (5001, 'AWZPlan');
INSERT INTO xplan_gml.enum_rp_art (wert, beschreibung) VALUES (6000, 'RaeumlicherTeilplan');
INSERT INTO xplan_gml.enum_rp_art (wert, beschreibung) VALUES (9999, 'Sonstiges');

TRUNCATE xplan_gml.enum_rp_bedeutsamkeit;
INSERT INTO xplan_gml.enum_rp_bedeutsamkeit (wert, beschreibung) VALUES (1000, 'Regional');
INSERT INTO xplan_gml.enum_rp_bedeutsamkeit (wert, beschreibung) VALUES (2000, 'Ueberregional');
INSERT INTO xplan_gml.enum_rp_bedeutsamkeit (wert, beschreibung) VALUES (3000, 'Grossraeumig');
INSERT INTO xplan_gml.enum_rp_bedeutsamkeit (wert, beschreibung) VALUES (4000, 'Landesweit');
INSERT INTO xplan_gml.enum_rp_bedeutsamkeit (wert, beschreibung) VALUES (5000, 'Bundesweit');
INSERT INTO xplan_gml.enum_rp_bedeutsamkeit (wert, beschreibung) VALUES (6000, 'Europaeisch');
INSERT INTO xplan_gml.enum_rp_bedeutsamkeit (wert, beschreibung) VALUES (7000, 'International');
INSERT INTO xplan_gml.enum_rp_bedeutsamkeit (wert, beschreibung) VALUES (8000, 'Flaechenerschliessend');
INSERT INTO xplan_gml.enum_rp_bedeutsamkeit (wert, beschreibung) VALUES (9000, 'Herausragend');

TRUNCATE xplan_gml.enum_rp_bergbaufolgenutzung;
INSERT INTO xplan_gml.enum_rp_bergbaufolgenutzung (wert, beschreibung) VALUES (1000, 'Landwirtschaft');
INSERT INTO xplan_gml.enum_rp_bergbaufolgenutzung (wert, beschreibung) VALUES (2000, 'Forstwirtschaft');
INSERT INTO xplan_gml.enum_rp_bergbaufolgenutzung (wert, beschreibung) VALUES (3000, 'Gruenlandbewirtschaftung');
INSERT INTO xplan_gml.enum_rp_bergbaufolgenutzung (wert, beschreibung) VALUES (4000, 'NaturLandschaft');
INSERT INTO xplan_gml.enum_rp_bergbaufolgenutzung (wert, beschreibung) VALUES (5000, 'Naturschutz');
INSERT INTO xplan_gml.enum_rp_bergbaufolgenutzung (wert, beschreibung) VALUES (6000, 'Erholung');
INSERT INTO xplan_gml.enum_rp_bergbaufolgenutzung (wert, beschreibung) VALUES (7000, 'Gewaesser');
INSERT INTO xplan_gml.enum_rp_bergbaufolgenutzung (wert, beschreibung) VALUES (8000, 'Verkehr');
INSERT INTO xplan_gml.enum_rp_bergbaufolgenutzung (wert, beschreibung) VALUES (9000, 'Altbergbau');
INSERT INTO xplan_gml.enum_rp_bergbaufolgenutzung (wert, beschreibung) VALUES (9999, 'SonstigeNutzung');

TRUNCATE xplan_gml.enum_rp_bergbauplanungtypen;
INSERT INTO xplan_gml.enum_rp_bergbauplanungtypen (wert, beschreibung) VALUES (1000, 'Lagerstaette');
INSERT INTO xplan_gml.enum_rp_bergbauplanungtypen (wert, beschreibung) VALUES (1100, 'Sicherung');
INSERT INTO xplan_gml.enum_rp_bergbauplanungtypen (wert, beschreibung) VALUES (1200, 'Gewinnung');
INSERT INTO xplan_gml.enum_rp_bergbauplanungtypen (wert, beschreibung) VALUES (1300, 'Abbaubereich');
INSERT INTO xplan_gml.enum_rp_bergbauplanungtypen (wert, beschreibung) VALUES (1400, 'Sicherheitszone');
INSERT INTO xplan_gml.enum_rp_bergbauplanungtypen (wert, beschreibung) VALUES (1500, 'AnlageEinrichtungBergbau');
INSERT INTO xplan_gml.enum_rp_bergbauplanungtypen (wert, beschreibung) VALUES (1600, 'Halde');
INSERT INTO xplan_gml.enum_rp_bergbauplanungtypen (wert, beschreibung) VALUES (1700, 'Sanierungsflaeche');
INSERT INTO xplan_gml.enum_rp_bergbauplanungtypen (wert, beschreibung) VALUES (1800, 'AnsiedlungUmsiedlung');
INSERT INTO xplan_gml.enum_rp_bergbauplanungtypen (wert, beschreibung) VALUES (1900, 'Bergbaufolgelandschaft');
INSERT INTO xplan_gml.enum_rp_bergbauplanungtypen (wert, beschreibung) VALUES (9999, 'SonstigeBergbauplanung');

TRUNCATE xplan_gml.enum_rp_besondereraumkategorietypen;
INSERT INTO xplan_gml.enum_rp_besondereraumkategorietypen (wert, beschreibung) VALUES (1000, 'Grenzgebiet');
INSERT INTO xplan_gml.enum_rp_besondereraumkategorietypen (wert, beschreibung) VALUES (2000, 'Bergbaufolgelandschaft');
INSERT INTO xplan_gml.enum_rp_besondereraumkategorietypen (wert, beschreibung) VALUES (3000, 'Braunkohlenfolgelandschaft');

TRUNCATE xplan_gml.enum_rp_besondererschienenverkehrtypen;
INSERT INTO xplan_gml.enum_rp_besondererschienenverkehrtypen (wert, beschreibung) VALUES (1000, 'Eingleisig');
INSERT INTO xplan_gml.enum_rp_besondererschienenverkehrtypen (wert, beschreibung) VALUES (1001, 'Zweigleisig');
INSERT INTO xplan_gml.enum_rp_besondererschienenverkehrtypen (wert, beschreibung) VALUES (1002, 'Mehrgleisig');
INSERT INTO xplan_gml.enum_rp_besondererschienenverkehrtypen (wert, beschreibung) VALUES (2000, 'OhneBetrieb');
INSERT INTO xplan_gml.enum_rp_besondererschienenverkehrtypen (wert, beschreibung) VALUES (3000, 'MitFernverkehrsfunktion');
INSERT INTO xplan_gml.enum_rp_besondererschienenverkehrtypen (wert, beschreibung) VALUES (3001, 'MitVerknuepfungsfunktionFuerOEPNV');
INSERT INTO xplan_gml.enum_rp_besondererschienenverkehrtypen (wert, beschreibung) VALUES (4000, 'ElektrischerBetrieb');
INSERT INTO xplan_gml.enum_rp_besondererschienenverkehrtypen (wert, beschreibung) VALUES (4001, 'ZuElektrifizieren');
INSERT INTO xplan_gml.enum_rp_besondererschienenverkehrtypen (wert, beschreibung) VALUES (5000, 'VerbesserungLeistungsfaehigkeit');
INSERT INTO xplan_gml.enum_rp_besondererschienenverkehrtypen (wert, beschreibung) VALUES (6000, 'RaeumlicheFreihaltungentwidmeterBahntrassen');
INSERT INTO xplan_gml.enum_rp_besondererschienenverkehrtypen (wert, beschreibung) VALUES (6001, 'NachnutzungstillgelegterStrecken');
INSERT INTO xplan_gml.enum_rp_besondererschienenverkehrtypen (wert, beschreibung) VALUES (7000, 'Personenverkehr');
INSERT INTO xplan_gml.enum_rp_besondererschienenverkehrtypen (wert, beschreibung) VALUES (7001, 'Gueterverkehr');
INSERT INTO xplan_gml.enum_rp_besondererschienenverkehrtypen (wert, beschreibung) VALUES (8000, 'Nahverkehr');
INSERT INTO xplan_gml.enum_rp_besondererschienenverkehrtypen (wert, beschreibung) VALUES (8001, 'Fernverkehr');

TRUNCATE xplan_gml.enum_rp_besondererstrassenverkehrtypen;
INSERT INTO xplan_gml.enum_rp_besondererstrassenverkehrtypen (wert, beschreibung) VALUES (1000, 'Zweistreifig');
INSERT INTO xplan_gml.enum_rp_besondererstrassenverkehrtypen (wert, beschreibung) VALUES (1001, 'Dreistreifig');
INSERT INTO xplan_gml.enum_rp_besondererstrassenverkehrtypen (wert, beschreibung) VALUES (1002, 'Vierstreifig');
INSERT INTO xplan_gml.enum_rp_besondererstrassenverkehrtypen (wert, beschreibung) VALUES (1003, 'Sechsstreifig');
INSERT INTO xplan_gml.enum_rp_besondererstrassenverkehrtypen (wert, beschreibung) VALUES (2000, 'Problembereich');
INSERT INTO xplan_gml.enum_rp_besondererstrassenverkehrtypen (wert, beschreibung) VALUES (3000, 'GruenbrueckeQuerungsmoeglichkeit');

TRUNCATE xplan_gml.enum_rp_besonderetourismuserholungtypen;
INSERT INTO xplan_gml.enum_rp_besonderetourismuserholungtypen (wert, beschreibung) VALUES (1000, 'Entwicklungsgebiet');
INSERT INTO xplan_gml.enum_rp_besonderetourismuserholungtypen (wert, beschreibung) VALUES (2000, 'Kernbereich');
INSERT INTO xplan_gml.enum_rp_besonderetourismuserholungtypen (wert, beschreibung) VALUES (3000, 'BesondereEntwicklungsaufgabe');

TRUNCATE xplan_gml.enum_rp_bodenschatztiefen;
INSERT INTO xplan_gml.enum_rp_bodenschatztiefen (wert, beschreibung) VALUES (1000, 'Oberflaechennah');
INSERT INTO xplan_gml.enum_rp_bodenschatztiefen (wert, beschreibung) VALUES (2000, 'Tiefliegend');

TRUNCATE xplan_gml.enum_rp_bodenschutztypen;
INSERT INTO xplan_gml.enum_rp_bodenschutztypen (wert, beschreibung) VALUES (1000, 'BeseitigungErheblicherBodenbelastung');
INSERT INTO xplan_gml.enum_rp_bodenschutztypen (wert, beschreibung) VALUES (2000, 'SicherungSanierungAltlasten');
INSERT INTO xplan_gml.enum_rp_bodenschutztypen (wert, beschreibung) VALUES (3000, 'Erosionsschutz');
INSERT INTO xplan_gml.enum_rp_bodenschutztypen (wert, beschreibung) VALUES (4000, 'Torferhalt');
INSERT INTO xplan_gml.enum_rp_bodenschutztypen (wert, beschreibung) VALUES (9999, 'SonstigerBodenschutz');

TRUNCATE xplan_gml.enum_rp_einzelhandeltypen;
INSERT INTO xplan_gml.enum_rp_einzelhandeltypen (wert, beschreibung) VALUES (1000, 'Einzelhandel');
INSERT INTO xplan_gml.enum_rp_einzelhandeltypen (wert, beschreibung) VALUES (2000, 'ZentralerVersorgungsbereich');
INSERT INTO xplan_gml.enum_rp_einzelhandeltypen (wert, beschreibung) VALUES (3000, 'ZentralerEinkaufsbereich');
INSERT INTO xplan_gml.enum_rp_einzelhandeltypen (wert, beschreibung) VALUES (4000, 'ZentrenrelevantesGrossprojekt');
INSERT INTO xplan_gml.enum_rp_einzelhandeltypen (wert, beschreibung) VALUES (5000, 'NichtzentrenrelevantesGrossprojekt');
INSERT INTO xplan_gml.enum_rp_einzelhandeltypen (wert, beschreibung) VALUES (6000, 'GrossflaechigerEinzelhandel');
INSERT INTO xplan_gml.enum_rp_einzelhandeltypen (wert, beschreibung) VALUES (7000, 'Fachmarktstandort');
INSERT INTO xplan_gml.enum_rp_einzelhandeltypen (wert, beschreibung) VALUES (8000, 'Ergaenzungsstandort');
INSERT INTO xplan_gml.enum_rp_einzelhandeltypen (wert, beschreibung) VALUES (9000, 'StaedtischerKernbereich');
INSERT INTO xplan_gml.enum_rp_einzelhandeltypen (wert, beschreibung) VALUES (9999, 'SonstigerEinzelhandel');

TRUNCATE xplan_gml.enum_rp_energieversorgungtypen;
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (1000, 'Leitungstrasse');
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (1001, 'Hochspannungsleitung');
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (1002, 'KabeltrasseNetzanbindung');
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (2000, 'Pipeline');
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (2001, 'Uebergabestation');
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (3000, 'Kraftwerk');
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (3001, 'Grosskraftwerk');
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (3002, 'Energiegewinnung');
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (4000, 'Energiespeicherung');
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (4001, 'VerstetigungSpeicherung');
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (4002, 'Untergrundspeicher');
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (5000, 'Umspannwerk');
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (6000, 'Raffinerie');
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (7000, 'Leitungsabbau');
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (8000, 'Korridor');
INSERT INTO xplan_gml.enum_rp_energieversorgungtypen (wert, beschreibung) VALUES (9999, 'SonstigeEnergieversorgung');

TRUNCATE xplan_gml.enum_rp_erholungtypen;
INSERT INTO xplan_gml.enum_rp_erholungtypen (wert, beschreibung) VALUES (1000, 'Erholung');
INSERT INTO xplan_gml.enum_rp_erholungtypen (wert, beschreibung) VALUES (2000, 'RuhigeErholungInNaturUndLandschaft');
INSERT INTO xplan_gml.enum_rp_erholungtypen (wert, beschreibung) VALUES (2001, 'LandschaftsbezogeneErholung');
INSERT INTO xplan_gml.enum_rp_erholungtypen (wert, beschreibung) VALUES (3000, 'ErholungMitStarkerInanspruchnahmedurchBevoelkerung');
INSERT INTO xplan_gml.enum_rp_erholungtypen (wert, beschreibung) VALUES (3001, 'InfrastrukturelleErholung');
INSERT INTO xplan_gml.enum_rp_erholungtypen (wert, beschreibung) VALUES (4000, 'Erholungswald');
INSERT INTO xplan_gml.enum_rp_erholungtypen (wert, beschreibung) VALUES (5000, 'Freizeitanlage');
INSERT INTO xplan_gml.enum_rp_erholungtypen (wert, beschreibung) VALUES (5001, 'Ferieneinrichtung');
INSERT INTO xplan_gml.enum_rp_erholungtypen (wert, beschreibung) VALUES (6000, 'ErholungslandschaftAlpen');
INSERT INTO xplan_gml.enum_rp_erholungtypen (wert, beschreibung) VALUES (7000, 'Kureinrichtung');
INSERT INTO xplan_gml.enum_rp_erholungtypen (wert, beschreibung) VALUES (9999, 'SonstigeErholung');

TRUNCATE xplan_gml.enum_rp_erneuerbareenergietypen;
INSERT INTO xplan_gml.enum_rp_erneuerbareenergietypen (wert, beschreibung) VALUES (1000, 'Windenergie');
INSERT INTO xplan_gml.enum_rp_erneuerbareenergietypen (wert, beschreibung) VALUES (2000, 'Solarenergie');
INSERT INTO xplan_gml.enum_rp_erneuerbareenergietypen (wert, beschreibung) VALUES (3000, 'Geothermie');
INSERT INTO xplan_gml.enum_rp_erneuerbareenergietypen (wert, beschreibung) VALUES (4000, 'Biomasse');
INSERT INTO xplan_gml.enum_rp_erneuerbareenergietypen (wert, beschreibung) VALUES (5000, 'Wasserkraft');
INSERT INTO xplan_gml.enum_rp_erneuerbareenergietypen (wert, beschreibung) VALUES (9999, 'SonstigeErneuerbareEnergie');

TRUNCATE xplan_gml.enum_rp_forstwirtschafttypen;
INSERT INTO xplan_gml.enum_rp_forstwirtschafttypen (wert, beschreibung) VALUES (1000, 'Wald');
INSERT INTO xplan_gml.enum_rp_forstwirtschafttypen (wert, beschreibung) VALUES (1001, 'Bannwald');
INSERT INTO xplan_gml.enum_rp_forstwirtschafttypen (wert, beschreibung) VALUES (1002, 'Schonwald');
INSERT INTO xplan_gml.enum_rp_forstwirtschafttypen (wert, beschreibung) VALUES (2000, 'Waldmehrung');
INSERT INTO xplan_gml.enum_rp_forstwirtschafttypen (wert, beschreibung) VALUES (2001, 'WaldmehrungErholung');
INSERT INTO xplan_gml.enum_rp_forstwirtschafttypen (wert, beschreibung) VALUES (2002, 'VergroesserungDesWaldanteils');
INSERT INTO xplan_gml.enum_rp_forstwirtschafttypen (wert, beschreibung) VALUES (3000, 'Waldschutz');
INSERT INTO xplan_gml.enum_rp_forstwirtschafttypen (wert, beschreibung) VALUES (3001, 'BesondereSchutzfunktionDesWaldes');
INSERT INTO xplan_gml.enum_rp_forstwirtschafttypen (wert, beschreibung) VALUES (4000, 'VonAufforstungFreizuhalten');
INSERT INTO xplan_gml.enum_rp_forstwirtschafttypen (wert, beschreibung) VALUES (9999, 'SonstigeForstwirtschaft');

TRUNCATE xplan_gml.enum_rp_funktionszuweisungtypen;
INSERT INTO xplan_gml.enum_rp_funktionszuweisungtypen (wert, beschreibung) VALUES (1000, 'Wohnen');
INSERT INTO xplan_gml.enum_rp_funktionszuweisungtypen (wert, beschreibung) VALUES (2000, 'Arbeit');
INSERT INTO xplan_gml.enum_rp_funktionszuweisungtypen (wert, beschreibung) VALUES (3000, 'GewerbeDienstleistung');
INSERT INTO xplan_gml.enum_rp_funktionszuweisungtypen (wert, beschreibung) VALUES (4000, 'Einzelhandel');
INSERT INTO xplan_gml.enum_rp_funktionszuweisungtypen (wert, beschreibung) VALUES (5000, 'Landwirtschaft');
INSERT INTO xplan_gml.enum_rp_funktionszuweisungtypen (wert, beschreibung) VALUES (6000, 'ErholungFremdenverkehr');
INSERT INTO xplan_gml.enum_rp_funktionszuweisungtypen (wert, beschreibung) VALUES (7000, 'Verteidigung');
INSERT INTO xplan_gml.enum_rp_funktionszuweisungtypen (wert, beschreibung) VALUES (8000, 'UeberoertlicheVersorgungsfunktionLaendlicherRaum');
INSERT INTO xplan_gml.enum_rp_funktionszuweisungtypen (wert, beschreibung) VALUES (9000, 'LaendlicheSiedlung');
INSERT INTO xplan_gml.enum_rp_funktionszuweisungtypen (wert, beschreibung) VALUES (9999, 'SonstigeFunktion');

TRUNCATE xplan_gml.enum_rp_gebietstyp;
INSERT INTO xplan_gml.enum_rp_gebietstyp (wert, beschreibung) VALUES (1000, 'Vorranggebiet');
INSERT INTO xplan_gml.enum_rp_gebietstyp (wert, beschreibung) VALUES (1001, 'Vorrangstandort');
INSERT INTO xplan_gml.enum_rp_gebietstyp (wert, beschreibung) VALUES (1100, 'Vorbehaltsgebiet');
INSERT INTO xplan_gml.enum_rp_gebietstyp (wert, beschreibung) VALUES (1101, 'Vorbehaltsstandort');
INSERT INTO xplan_gml.enum_rp_gebietstyp (wert, beschreibung) VALUES (1200, 'Eignungsgebiet');
INSERT INTO xplan_gml.enum_rp_gebietstyp (wert, beschreibung) VALUES (1300, 'VorrangundEignungsgebiet');
INSERT INTO xplan_gml.enum_rp_gebietstyp (wert, beschreibung) VALUES (1400, 'Ausschlussgebiet');
INSERT INTO xplan_gml.enum_rp_gebietstyp (wert, beschreibung) VALUES (1500, 'Vorsorgegebiet');
INSERT INTO xplan_gml.enum_rp_gebietstyp (wert, beschreibung) VALUES (1501, 'Vorsorgestandort');
INSERT INTO xplan_gml.enum_rp_gebietstyp (wert, beschreibung) VALUES (1600, 'Vorzugsraum');
INSERT INTO xplan_gml.enum_rp_gebietstyp (wert, beschreibung) VALUES (1700, 'Potenzialgebiet');
INSERT INTO xplan_gml.enum_rp_gebietstyp (wert, beschreibung) VALUES (1800, 'Schwerpunktraum');
INSERT INTO xplan_gml.enum_rp_gebietstyp (wert, beschreibung) VALUES (9999, 'SonstigesGebiet');

TRUNCATE xplan_gml.enum_rp_hochwasserschutztypen;
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1000, 'Hochwasserschutz');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1001, 'TechnischerHochwasserschutz');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1100, 'Hochwasserrueckhaltebecken');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1101, 'HochwasserrueckhaltebeckenPolder');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1102, 'HochwasserrueckhaltebeckenBauwerk');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1200, 'RisikobereichHochwasser');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1300, 'Kuestenhochwasserschutz');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1301, 'Deich');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1302, 'Deichrueckverlegung');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1303, 'DeichgeschuetztesGebiet');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1400, 'Sperrwerk');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1500, 'HochwGefaehrdeteKuestenniederung');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1600, 'Ueberschwemmungsgebiet');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1700, 'UeberschwemmungsgefaehrdeterBereich');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1800, 'Retentionsraum');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (1801, 'PotenziellerRetentionsraum');
INSERT INTO xplan_gml.enum_rp_hochwasserschutztypen (wert, beschreibung) VALUES (9999, 'SonstigerHochwasserschutz');

TRUNCATE xplan_gml.enum_rp_industriegewerbetypen;
INSERT INTO xplan_gml.enum_rp_industriegewerbetypen (wert, beschreibung) VALUES (1000, 'Industrie');
INSERT INTO xplan_gml.enum_rp_industriegewerbetypen (wert, beschreibung) VALUES (1001, 'IndustrielleAnlage');
INSERT INTO xplan_gml.enum_rp_industriegewerbetypen (wert, beschreibung) VALUES (2000, 'Gewerbe');
INSERT INTO xplan_gml.enum_rp_industriegewerbetypen (wert, beschreibung) VALUES (2001, 'GewerblicherBereich');
INSERT INTO xplan_gml.enum_rp_industriegewerbetypen (wert, beschreibung) VALUES (2002, 'Gewerbepark');
INSERT INTO xplan_gml.enum_rp_industriegewerbetypen (wert, beschreibung) VALUES (2003, 'DienstleistungGewerbeZentrum');
INSERT INTO xplan_gml.enum_rp_industriegewerbetypen (wert, beschreibung) VALUES (3000, 'GewerbeIndustrie');
INSERT INTO xplan_gml.enum_rp_industriegewerbetypen (wert, beschreibung) VALUES (3001, 'BedeutsamerEntwicklungsstandortGewerbeIndustrie');
INSERT INTO xplan_gml.enum_rp_industriegewerbetypen (wert, beschreibung) VALUES (4000, 'SicherungundEntwicklungvonArbeitsstaetten');
INSERT INTO xplan_gml.enum_rp_industriegewerbetypen (wert, beschreibung) VALUES (5000, 'FlaechenintensivesGrossvorhaben');
INSERT INTO xplan_gml.enum_rp_industriegewerbetypen (wert, beschreibung) VALUES (6000, 'BetriebsanlageBergbau');
INSERT INTO xplan_gml.enum_rp_industriegewerbetypen (wert, beschreibung) VALUES (7000, 'HafenorientierteWirtschaftlicheAnlage');
INSERT INTO xplan_gml.enum_rp_industriegewerbetypen (wert, beschreibung) VALUES (8000, 'TankRastanlage');
INSERT INTO xplan_gml.enum_rp_industriegewerbetypen (wert, beschreibung) VALUES (9000, 'BereichFuerGewerblicheUndIndustrielleNutzungGIB');
INSERT INTO xplan_gml.enum_rp_industriegewerbetypen (wert, beschreibung) VALUES (9999, 'SonstigeIndustrieGewerbe');

TRUNCATE xplan_gml.enum_rp_klimaschutztypen;
INSERT INTO xplan_gml.enum_rp_klimaschutztypen (wert, beschreibung) VALUES (1000, 'Kaltluft');
INSERT INTO xplan_gml.enum_rp_klimaschutztypen (wert, beschreibung) VALUES (2000, 'Frischluft');
INSERT INTO xplan_gml.enum_rp_klimaschutztypen (wert, beschreibung) VALUES (3000, 'BesondereKlimaschutzfunktion');
INSERT INTO xplan_gml.enum_rp_klimaschutztypen (wert, beschreibung) VALUES (9999, 'SonstigeLufttypen');

TRUNCATE xplan_gml.enum_rp_kommunikationtypen;
INSERT INTO xplan_gml.enum_rp_kommunikationtypen (wert, beschreibung) VALUES (1000, 'Richtfunkstrecke');
INSERT INTO xplan_gml.enum_rp_kommunikationtypen (wert, beschreibung) VALUES (2000, 'Fernmeldeanlage');
INSERT INTO xplan_gml.enum_rp_kommunikationtypen (wert, beschreibung) VALUES (2001, 'SendeEmpfangsstation');
INSERT INTO xplan_gml.enum_rp_kommunikationtypen (wert, beschreibung) VALUES (2002, 'TonFernsehsender');
INSERT INTO xplan_gml.enum_rp_kommunikationtypen (wert, beschreibung) VALUES (9999, 'SonstigeKommunikation');

TRUNCATE xplan_gml.enum_rp_kulturlandschafttypen;
INSERT INTO xplan_gml.enum_rp_kulturlandschafttypen (wert, beschreibung) VALUES (1000, 'KulturellesSachgut');
INSERT INTO xplan_gml.enum_rp_kulturlandschafttypen (wert, beschreibung) VALUES (2000, 'Welterbe');
INSERT INTO xplan_gml.enum_rp_kulturlandschafttypen (wert, beschreibung) VALUES (3000, 'KulturerbeLandschaft');
INSERT INTO xplan_gml.enum_rp_kulturlandschafttypen (wert, beschreibung) VALUES (4000, 'KulturDenkmalpflege');
INSERT INTO xplan_gml.enum_rp_kulturlandschafttypen (wert, beschreibung) VALUES (9999, 'SonstigeKulturlandschaftTypen');

TRUNCATE xplan_gml.enum_rp_laermschutztypen;
INSERT INTO xplan_gml.enum_rp_laermschutztypen (wert, beschreibung) VALUES (1000, 'Laermbereich');
INSERT INTO xplan_gml.enum_rp_laermschutztypen (wert, beschreibung) VALUES (1001, 'Laermschutzbereich');
INSERT INTO xplan_gml.enum_rp_laermschutztypen (wert, beschreibung) VALUES (2000, 'Siedlungsbeschraenkungsbereich');
INSERT INTO xplan_gml.enum_rp_laermschutztypen (wert, beschreibung) VALUES (3000, 'ZoneA');
INSERT INTO xplan_gml.enum_rp_laermschutztypen (wert, beschreibung) VALUES (4000, 'ZoneB');
INSERT INTO xplan_gml.enum_rp_laermschutztypen (wert, beschreibung) VALUES (5000, 'ZoneC');
INSERT INTO xplan_gml.enum_rp_laermschutztypen (wert, beschreibung) VALUES (9999, 'SonstigerLaermschutzBauschutz');

TRUNCATE xplan_gml.enum_rp_landwirtschafttypen;
INSERT INTO xplan_gml.enum_rp_landwirtschafttypen (wert, beschreibung) VALUES (1000, 'LandwirtschaftlicheNutzung');
INSERT INTO xplan_gml.enum_rp_landwirtschafttypen (wert, beschreibung) VALUES (1001, 'KernzoneLandwirtschaft');
INSERT INTO xplan_gml.enum_rp_landwirtschafttypen (wert, beschreibung) VALUES (2000, 'IntensivLandwirtschaft');
INSERT INTO xplan_gml.enum_rp_landwirtschafttypen (wert, beschreibung) VALUES (3000, 'Fischerei');
INSERT INTO xplan_gml.enum_rp_landwirtschafttypen (wert, beschreibung) VALUES (4000, 'Weinbau');
INSERT INTO xplan_gml.enum_rp_landwirtschafttypen (wert, beschreibung) VALUES (5000, 'AufGrundHohenErtragspotenzials');
INSERT INTO xplan_gml.enum_rp_landwirtschafttypen (wert, beschreibung) VALUES (6000, 'AufGrundBesondererFunktionen');
INSERT INTO xplan_gml.enum_rp_landwirtschafttypen (wert, beschreibung) VALUES (7000, 'Gruenlandbewirtschaftung');
INSERT INTO xplan_gml.enum_rp_landwirtschafttypen (wert, beschreibung) VALUES (8000, 'Sonderkultur');
INSERT INTO xplan_gml.enum_rp_landwirtschafttypen (wert, beschreibung) VALUES (9999, 'SonstigeLandwirtschaft');

TRUNCATE xplan_gml.enum_rp_luftverkehrtypen;
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (1000, 'Flughafen');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (1001, 'Verkehrsflughafen');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (1002, 'Regionalflughafen');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (1003, 'InternationalerFlughafen');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (1004, 'InternationalerVerkehrsflughafen');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (1005, 'Flughafenentwicklung');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (2000, 'Flugplatz');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (2001, 'Regionalflugplatz');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (2002, 'Segelflugplatz');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (2003, 'SonstigerFlugplatz');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (3000, 'Bauschutzbereich');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (4000, 'Militaerflughafen');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (5000, 'Landeplatz');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (5001, 'Verkehrslandeplatz');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (5002, 'Hubschrauberlandeplatz');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (5003, 'Landebahn');
INSERT INTO xplan_gml.enum_rp_luftverkehrtypen (wert, beschreibung) VALUES (9999, 'SonstigerLuftverkehr');

TRUNCATE xplan_gml.enum_rp_naturlandschafttypen;
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1000, 'NaturLandschaft');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1100, 'NaturschutzLandschaftspflege');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1101, 'NaturschutzLandschaftspflegeAufGewaessern');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1200, 'Flurdurchgruenung');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1300, 'UnzerschnitteneRaeume');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1301, 'UnzerschnitteneVerkehrsarmeRaeume');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1400, 'Feuchtgebiet');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1500, 'OekologischesVerbundssystem');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1501, 'OekologischerRaum');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1600, 'VerbesserungLandschaftsstrukturNaturhaushalt');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1700, 'Biotop');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1701, 'Biotopverbund');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1702, 'Biotopverbundachse');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1703, 'ArtenBiotopschutz');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1704, 'Regionalpark');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1800, 'KompensationEntwicklung');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (1900, 'GruenlandBewirtschaftungPflegeEntwicklung');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (2000, 'Landschaftsstruktur');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (2100, 'LandschaftErholung');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (2200, 'Landschaftspraegend');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (2300, 'SchutzderNatur');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (2400, 'SchutzdesLandschaftsbildes');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (2500, 'Alpenpark');
INSERT INTO xplan_gml.enum_rp_naturlandschafttypen (wert, beschreibung) VALUES (9999, 'SonstigerNaturLandschaftSchutz');

TRUNCATE xplan_gml.enum_rp_primaerenergietypen;
INSERT INTO xplan_gml.enum_rp_primaerenergietypen (wert, beschreibung) VALUES (1000, 'Erdoel');
INSERT INTO xplan_gml.enum_rp_primaerenergietypen (wert, beschreibung) VALUES (2000, 'Gas');
INSERT INTO xplan_gml.enum_rp_primaerenergietypen (wert, beschreibung) VALUES (2001, 'Ferngas');
INSERT INTO xplan_gml.enum_rp_primaerenergietypen (wert, beschreibung) VALUES (3000, 'Fernwaerme');
INSERT INTO xplan_gml.enum_rp_primaerenergietypen (wert, beschreibung) VALUES (4000, 'Kraftstoff');
INSERT INTO xplan_gml.enum_rp_primaerenergietypen (wert, beschreibung) VALUES (5000, 'Kohle');
INSERT INTO xplan_gml.enum_rp_primaerenergietypen (wert, beschreibung) VALUES (6000, 'Wasser');
INSERT INTO xplan_gml.enum_rp_primaerenergietypen (wert, beschreibung) VALUES (7000, 'Kernenergie');
INSERT INTO xplan_gml.enum_rp_primaerenergietypen (wert, beschreibung) VALUES (8000, 'Reststoffverwertung');
INSERT INTO xplan_gml.enum_rp_primaerenergietypen (wert, beschreibung) VALUES (9000, 'ErneuerbareEnergie');
INSERT INTO xplan_gml.enum_rp_primaerenergietypen (wert, beschreibung) VALUES (9001, 'Windenergie');
INSERT INTO xplan_gml.enum_rp_primaerenergietypen (wert, beschreibung) VALUES (9999, 'SonstigePrimaerenergie');

TRUNCATE xplan_gml.enum_rp_radwegwanderwegtypen;
INSERT INTO xplan_gml.enum_rp_radwegwanderwegtypen (wert, beschreibung) VALUES (1000, 'Wanderweg');
INSERT INTO xplan_gml.enum_rp_radwegwanderwegtypen (wert, beschreibung) VALUES (1001, 'Fernwanderweg');
INSERT INTO xplan_gml.enum_rp_radwegwanderwegtypen (wert, beschreibung) VALUES (2000, 'Radwandern');
INSERT INTO xplan_gml.enum_rp_radwegwanderwegtypen (wert, beschreibung) VALUES (2001, 'Fernradweg');
INSERT INTO xplan_gml.enum_rp_radwegwanderwegtypen (wert, beschreibung) VALUES (3000, 'Reiten');
INSERT INTO xplan_gml.enum_rp_radwegwanderwegtypen (wert, beschreibung) VALUES (4000, 'Wasserwandern');
INSERT INTO xplan_gml.enum_rp_radwegwanderwegtypen (wert, beschreibung) VALUES (9999, 'SonstigerWanderweg');

TRUNCATE xplan_gml.enum_rp_raumkategorietypen;
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1000, 'Ordnungsraum');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1001, 'OrdnungsraumTourismusErholung');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1100, 'Verdichtungsraum');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1101, 'KernzoneVerdichtungsraum');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1102, 'RandzoneVerdichtungsraum');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1103, 'Ballungskernzone');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1104, 'Ballungsrandzone');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1105, 'HochverdichteterRaum');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1106, 'StadtUmlandBereichVerdichtungsraum');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1200, 'LaendlicherRaum');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1201, 'VerdichteterBereichimLaendlichenRaum');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1202, 'Gestaltungsraum');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1203, 'LaendlicherGestaltungsraum');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1300, 'StadtUmlandRaum');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1301, 'StadtUmlandBereichLaendlicherRaum');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1400, 'AbgrenzungOrdnungsraum');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1500, 'DuennbesiedeltesAbgelegenesGebiet');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1600, 'Umkreis10KM');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1700, 'RaummitbesonderemHandlungsbedarf');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1800, 'Funktionsraum');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (1900, 'GrenzeWirtschaftsraum');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (2000, 'Funktionsschwerpunkt');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (2100, 'Grundversorgung');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (2200, 'Alpengebiet');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (2300, 'RaeumeMitGuenstigenEntwicklungsvoraussetzungen');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (2400, 'RaeumeMitAusgeglichenenEntwicklungspotenzialen');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (2500, 'RaeumeMitBesonderenEntwicklungsaufgaben');
INSERT INTO xplan_gml.enum_rp_raumkategorietypen (wert, beschreibung) VALUES (9999, 'SonstigeRaumkategorie');

TRUNCATE xplan_gml.enum_rp_rechtscharakter;
INSERT INTO xplan_gml.enum_rp_rechtscharakter (wert, beschreibung) VALUES (1000, 'ZielDerRaumordnung');
INSERT INTO xplan_gml.enum_rp_rechtscharakter (wert, beschreibung) VALUES (2000, 'GrundsatzDerRaumordnung');
INSERT INTO xplan_gml.enum_rp_rechtscharakter (wert, beschreibung) VALUES (3000, 'NachrichtlicheUebernahme');
INSERT INTO xplan_gml.enum_rp_rechtscharakter (wert, beschreibung) VALUES (4000, 'NachrichtlicheUebernahmeZiel');
INSERT INTO xplan_gml.enum_rp_rechtscharakter (wert, beschreibung) VALUES (5000, 'NachrichtlicheUebernahmeGrundsatz');
INSERT INTO xplan_gml.enum_rp_rechtscharakter (wert, beschreibung) VALUES (6000, 'NurInformationsgehalt');
INSERT INTO xplan_gml.enum_rp_rechtscharakter (wert, beschreibung) VALUES (7000, 'TextlichesZiel');
INSERT INTO xplan_gml.enum_rp_rechtscharakter (wert, beschreibung) VALUES (8000, 'ZielundGrundsatz');
INSERT INTO xplan_gml.enum_rp_rechtscharakter (wert, beschreibung) VALUES (9000, 'Vorschlag');
INSERT INTO xplan_gml.enum_rp_rechtscharakter (wert, beschreibung) VALUES (9998, 'Unbekannt');

TRUNCATE xplan_gml.enum_rp_rechtsstand;
INSERT INTO xplan_gml.enum_rp_rechtsstand (wert, beschreibung) VALUES (1000, 'Aufstellungsbeschluss');
INSERT INTO xplan_gml.enum_rp_rechtsstand (wert, beschreibung) VALUES (2000, 'Entwurf');
INSERT INTO xplan_gml.enum_rp_rechtsstand (wert, beschreibung) VALUES (2001, 'EntwurfGenehmigt');
INSERT INTO xplan_gml.enum_rp_rechtsstand (wert, beschreibung) VALUES (2002, 'EntwurfGeaendert');
INSERT INTO xplan_gml.enum_rp_rechtsstand (wert, beschreibung) VALUES (2003, 'EntwurfAufgegeben');
INSERT INTO xplan_gml.enum_rp_rechtsstand (wert, beschreibung) VALUES (2004, 'EntwurfRuht');
INSERT INTO xplan_gml.enum_rp_rechtsstand (wert, beschreibung) VALUES (3000, 'Plan');
INSERT INTO xplan_gml.enum_rp_rechtsstand (wert, beschreibung) VALUES (4000, 'Inkraftgetreten');
INSERT INTO xplan_gml.enum_rp_rechtsstand (wert, beschreibung) VALUES (5000, 'AllgemeinePlanungsabsicht');
INSERT INTO xplan_gml.enum_rp_rechtsstand (wert, beschreibung) VALUES (6000, 'AusserKraft');
INSERT INTO xplan_gml.enum_rp_rechtsstand (wert, beschreibung) VALUES (7000, 'PlanUngueltig');

TRUNCATE xplan_gml.enum_rp_rohstofftypen;
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (1000, 'Anhydritstein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (1100, 'Baryt');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (1200, 'BasaltDiabas');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (1300, 'Bentonit');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (1400, 'Blaehton');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (1500, 'Braunkohle');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (1600, 'Buntsandstein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (1700, 'Dekostein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (1800, 'Diorit');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (1900, 'Dolomitstein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (2000, 'Erdgas');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (2100, 'Erdoel');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (2200, 'Erz');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (2300, 'Feldspat');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (2400, 'Festgestein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (2500, 'Flussspat');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (2600, 'Gangquarz');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (2700, 'Gipsstein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (2800, 'Gneis');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (2900, 'Granit');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (3000, 'Grauwacke');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (3100, 'Hartgestein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (3200, 'KalkKalktuffKreide');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (3300, 'Kalkmergelstein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (3400, 'Kalkstein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (3500, 'Kaolin');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (3600, 'Karbonatgestein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (3700, 'Kies');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (3800, 'Kieselgur');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (3900, 'KieshaltigerSand');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (4000, 'KiesSand');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (4100, 'Klei');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (4200, 'Kristallin');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (4300, 'Kupfer');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (4400, 'Lehm');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (4500, 'Marmor');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (4600, 'Mergel');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (4700, 'Mergelstein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (4800, 'MikrogranitGranitporphyr');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (4900, 'Monzonit');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (5000, 'Muschelkalk');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (5100, 'Naturstein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (5200, 'Naturwerkstein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (5300, 'Oelschiefer');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (5400, 'Pegmatitsand');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (5500, 'Quarzit');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (5600, 'Quarzsand');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (5700, 'Rhyolith');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (5800, 'RhyolithQuarzporphyr');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (5900, 'Salz');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (6000, 'Sand');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (6100, 'Sandstein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (6200, 'Spezialton');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (6300, 'SteineundErden');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (6400, 'Steinkohle');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (6500, 'Ton');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (6600, 'Tonstein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (6700, 'Torf');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (6800, 'TuffBimsstein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (6900, 'Uran');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (7000, 'Vulkanit');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (7100, 'Werkstein');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (7200, 'Andesit');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (7300, 'Formsand');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (7400, 'Gabbro');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (7500, 'MikrodioritAndesit');
INSERT INTO xplan_gml.enum_rp_rohstofftypen (wert, beschreibung) VALUES (9999, 'Sonstiges');

TRUNCATE xplan_gml.enum_rp_schienenverkehrtypen;
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (1000, 'Schienenverkehr');
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (1001, 'Eisenbahnstrecke');
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (1002, 'Haupteisenbahnstrecke');
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (1100, 'Trasse');
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (1200, 'Schienennetz');
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (1300, 'Stadtbahn');
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (1301, 'Strassenbahn');
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (1302, 'SBahn');
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (1303, 'UBahn');
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (1400, 'AnschlussgleisIndustrieGewerbe');
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (1500, 'Haltepunkt');
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (1600, 'Bahnhof');
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (1700, 'Hochgeschwindigkeitsverkehr');
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (1800, 'Bahnbetriebsgelaende');
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (1801, 'AnlagemitgrossemFlaechenbedarf');
INSERT INTO xplan_gml.enum_rp_schienenverkehrtypen (wert, beschreibung) VALUES (9999, 'SonstigerSchienenverkehr');

TRUNCATE xplan_gml.enum_rp_sonstverkehrtypen;
INSERT INTO xplan_gml.enum_rp_sonstverkehrtypen (wert, beschreibung) VALUES (1000, 'Verkehrsanlage');
INSERT INTO xplan_gml.enum_rp_sonstverkehrtypen (wert, beschreibung) VALUES (1100, 'Gueterverkehrszentrum');
INSERT INTO xplan_gml.enum_rp_sonstverkehrtypen (wert, beschreibung) VALUES (1200, 'Logistikzentrum');
INSERT INTO xplan_gml.enum_rp_sonstverkehrtypen (wert, beschreibung) VALUES (1300, 'TerminalkombinierterVerkehr');
INSERT INTO xplan_gml.enum_rp_sonstverkehrtypen (wert, beschreibung) VALUES (1400, 'OEPNV');
INSERT INTO xplan_gml.enum_rp_sonstverkehrtypen (wert, beschreibung) VALUES (1500, 'VerknuepfungspunktBahnBus');
INSERT INTO xplan_gml.enum_rp_sonstverkehrtypen (wert, beschreibung) VALUES (1600, 'ParkandRideBikeandRide');
INSERT INTO xplan_gml.enum_rp_sonstverkehrtypen (wert, beschreibung) VALUES (1700, 'Faehrverkehr');
INSERT INTO xplan_gml.enum_rp_sonstverkehrtypen (wert, beschreibung) VALUES (1800, 'Infrastrukturkorridor');
INSERT INTO xplan_gml.enum_rp_sonstverkehrtypen (wert, beschreibung) VALUES (1900, 'Tunnel');
INSERT INTO xplan_gml.enum_rp_sonstverkehrtypen (wert, beschreibung) VALUES (2000, 'NeueVerkehrstechniken');
INSERT INTO xplan_gml.enum_rp_sonstverkehrtypen (wert, beschreibung) VALUES (2001, 'Teststrecke');
INSERT INTO xplan_gml.enum_rp_sonstverkehrtypen (wert, beschreibung) VALUES (9999, 'SonstigerVerkehr');

TRUNCATE xplan_gml.enum_rp_sozialeinfrastrukturtypen;
INSERT INTO xplan_gml.enum_rp_sozialeinfrastrukturtypen (wert, beschreibung) VALUES (1000, 'Kultur');
INSERT INTO xplan_gml.enum_rp_sozialeinfrastrukturtypen (wert, beschreibung) VALUES (2000, 'Sozialeinrichtung');
INSERT INTO xplan_gml.enum_rp_sozialeinfrastrukturtypen (wert, beschreibung) VALUES (3000, 'Gesundheit');
INSERT INTO xplan_gml.enum_rp_sozialeinfrastrukturtypen (wert, beschreibung) VALUES (3001, 'Krankenhaus');
INSERT INTO xplan_gml.enum_rp_sozialeinfrastrukturtypen (wert, beschreibung) VALUES (4000, 'BildungForschung');
INSERT INTO xplan_gml.enum_rp_sozialeinfrastrukturtypen (wert, beschreibung) VALUES (4001, 'Hochschule');
INSERT INTO xplan_gml.enum_rp_sozialeinfrastrukturtypen (wert, beschreibung) VALUES (5000, 'Polizei');
INSERT INTO xplan_gml.enum_rp_sozialeinfrastrukturtypen (wert, beschreibung) VALUES (9999, 'SonstigeSozialeInfrastruktur');

TRUNCATE xplan_gml.enum_rp_spannungtypen;
INSERT INTO xplan_gml.enum_rp_spannungtypen (wert, beschreibung) VALUES (1000, '110KV');
INSERT INTO xplan_gml.enum_rp_spannungtypen (wert, beschreibung) VALUES (2000, '220KV');
INSERT INTO xplan_gml.enum_rp_spannungtypen (wert, beschreibung) VALUES (3000, '330KV');
INSERT INTO xplan_gml.enum_rp_spannungtypen (wert, beschreibung) VALUES (4000, '380KV');

TRUNCATE xplan_gml.enum_rp_sperrgebiettypen;
INSERT INTO xplan_gml.enum_rp_sperrgebiettypen (wert, beschreibung) VALUES (1000, 'Verteidigung');
INSERT INTO xplan_gml.enum_rp_sperrgebiettypen (wert, beschreibung) VALUES (2000, 'SondergebietBund');
INSERT INTO xplan_gml.enum_rp_sperrgebiettypen (wert, beschreibung) VALUES (3000, 'Warngebiet');
INSERT INTO xplan_gml.enum_rp_sperrgebiettypen (wert, beschreibung) VALUES (4000, 'MilitaerischeEinrichtung');
INSERT INTO xplan_gml.enum_rp_sperrgebiettypen (wert, beschreibung) VALUES (4001, 'GrosseMilitaerischeAnlage');
INSERT INTO xplan_gml.enum_rp_sperrgebiettypen (wert, beschreibung) VALUES (5000, 'MilitaerischeLiegenschaft');
INSERT INTO xplan_gml.enum_rp_sperrgebiettypen (wert, beschreibung) VALUES (6000, 'Konversionsflaeche');
INSERT INTO xplan_gml.enum_rp_sperrgebiettypen (wert, beschreibung) VALUES (9999, 'SonstigesSperrgebiet');

TRUNCATE xplan_gml.enum_rp_spezifischegrenzetypen;
INSERT INTO xplan_gml.enum_rp_spezifischegrenzetypen (wert, beschreibung) VALUES (1000, 'Zwoelfmeilenzone');
INSERT INTO xplan_gml.enum_rp_spezifischegrenzetypen (wert, beschreibung) VALUES (1001, 'BegrenzungDesKuestenmeeres');
INSERT INTO xplan_gml.enum_rp_spezifischegrenzetypen (wert, beschreibung) VALUES (2000, 'VerlaufUmstritten');
INSERT INTO xplan_gml.enum_rp_spezifischegrenzetypen (wert, beschreibung) VALUES (3000, 'GrenzeDtAusschlWirtschaftszone');
INSERT INTO xplan_gml.enum_rp_spezifischegrenzetypen (wert, beschreibung) VALUES (4000, 'MittlereTideHochwasserlinie');
INSERT INTO xplan_gml.enum_rp_spezifischegrenzetypen (wert, beschreibung) VALUES (5000, 'PlanungsregionsgrenzeRegion');
INSERT INTO xplan_gml.enum_rp_spezifischegrenzetypen (wert, beschreibung) VALUES (6000, 'PlanungsregionsgrenzeLand');
INSERT INTO xplan_gml.enum_rp_spezifischegrenzetypen (wert, beschreibung) VALUES (7000, 'GrenzeBraunkohlenplan');
INSERT INTO xplan_gml.enum_rp_spezifischegrenzetypen (wert, beschreibung) VALUES (8000, 'Grenzuebergangsstelle');

TRUNCATE xplan_gml.enum_rp_sportanlagetypen;
INSERT INTO xplan_gml.enum_rp_sportanlagetypen (wert, beschreibung) VALUES (1000, 'Sportanlage');
INSERT INTO xplan_gml.enum_rp_sportanlagetypen (wert, beschreibung) VALUES (2000, 'Wassersport');
INSERT INTO xplan_gml.enum_rp_sportanlagetypen (wert, beschreibung) VALUES (3000, 'Motorsport');
INSERT INTO xplan_gml.enum_rp_sportanlagetypen (wert, beschreibung) VALUES (4000, 'Flugsport');
INSERT INTO xplan_gml.enum_rp_sportanlagetypen (wert, beschreibung) VALUES (5000, 'Reitsport');
INSERT INTO xplan_gml.enum_rp_sportanlagetypen (wert, beschreibung) VALUES (6000, 'Golfsport');
INSERT INTO xplan_gml.enum_rp_sportanlagetypen (wert, beschreibung) VALUES (7000, 'Sportzentrum');
INSERT INTO xplan_gml.enum_rp_sportanlagetypen (wert, beschreibung) VALUES (9999, 'SonstigeSportanlage');

TRUNCATE xplan_gml.enum_rp_strassenverkehrtypen;
INSERT INTO xplan_gml.enum_rp_strassenverkehrtypen (wert, beschreibung) VALUES (1000, 'Strassenverkehr');
INSERT INTO xplan_gml.enum_rp_strassenverkehrtypen (wert, beschreibung) VALUES (1001, 'Hauptverkehrsstrasse');
INSERT INTO xplan_gml.enum_rp_strassenverkehrtypen (wert, beschreibung) VALUES (1002, 'Autobahn');
INSERT INTO xplan_gml.enum_rp_strassenverkehrtypen (wert, beschreibung) VALUES (1003, 'Bundesstrasse');
INSERT INTO xplan_gml.enum_rp_strassenverkehrtypen (wert, beschreibung) VALUES (1004, 'Staatsstrasse');
INSERT INTO xplan_gml.enum_rp_strassenverkehrtypen (wert, beschreibung) VALUES (1005, 'Landesstrasse');
INSERT INTO xplan_gml.enum_rp_strassenverkehrtypen (wert, beschreibung) VALUES (1006, 'Kreisstrasse');
INSERT INTO xplan_gml.enum_rp_strassenverkehrtypen (wert, beschreibung) VALUES (1007, 'Fernstrasse');
INSERT INTO xplan_gml.enum_rp_strassenverkehrtypen (wert, beschreibung) VALUES (2000, 'Trasse');
INSERT INTO xplan_gml.enum_rp_strassenverkehrtypen (wert, beschreibung) VALUES (3000, 'Strassennetz');
INSERT INTO xplan_gml.enum_rp_strassenverkehrtypen (wert, beschreibung) VALUES (4000, 'Busverkehr');
INSERT INTO xplan_gml.enum_rp_strassenverkehrtypen (wert, beschreibung) VALUES (5000, 'Anschlussstelle');
INSERT INTO xplan_gml.enum_rp_strassenverkehrtypen (wert, beschreibung) VALUES (6000, 'Strassentunnel');
INSERT INTO xplan_gml.enum_rp_strassenverkehrtypen (wert, beschreibung) VALUES (9999, 'SonstigerStrassenverkehr');

TRUNCATE xplan_gml.enum_rp_tourismustypen;
INSERT INTO xplan_gml.enum_rp_tourismustypen (wert, beschreibung) VALUES (1000, 'Tourismus');
INSERT INTO xplan_gml.enum_rp_tourismustypen (wert, beschreibung) VALUES (2000, 'Kuestenraum');
INSERT INTO xplan_gml.enum_rp_tourismustypen (wert, beschreibung) VALUES (9999, 'SonstigerTourismus');

TRUNCATE xplan_gml.enum_rp_verfahren;
INSERT INTO xplan_gml.enum_rp_verfahren (wert, beschreibung) VALUES (1000, 'Aenderung');
INSERT INTO xplan_gml.enum_rp_verfahren (wert, beschreibung) VALUES (2000, 'Teilfortschreibung');
INSERT INTO xplan_gml.enum_rp_verfahren (wert, beschreibung) VALUES (3000, 'Neuaufstellung');
INSERT INTO xplan_gml.enum_rp_verfahren (wert, beschreibung) VALUES (4000, 'Gesamtfortschreibung');
INSERT INTO xplan_gml.enum_rp_verfahren (wert, beschreibung) VALUES (5000, 'Aktualisierung');

TRUNCATE xplan_gml.enum_rp_verkehrstatus;
INSERT INTO xplan_gml.enum_rp_verkehrstatus (wert, beschreibung) VALUES (1000, 'Ausbau');
INSERT INTO xplan_gml.enum_rp_verkehrstatus (wert, beschreibung) VALUES (1001, 'LinienfuehrungOffen');
INSERT INTO xplan_gml.enum_rp_verkehrstatus (wert, beschreibung) VALUES (2000, 'Sicherung');
INSERT INTO xplan_gml.enum_rp_verkehrstatus (wert, beschreibung) VALUES (3000, 'Neubau');
INSERT INTO xplan_gml.enum_rp_verkehrstatus (wert, beschreibung) VALUES (4000, 'ImBau');
INSERT INTO xplan_gml.enum_rp_verkehrstatus (wert, beschreibung) VALUES (5000, 'VorhPlanfestgestLinienbestGrobtrasse');
INSERT INTO xplan_gml.enum_rp_verkehrstatus (wert, beschreibung) VALUES (6000, 'BedarfsplanmassnahmeOhneRaeumlFestlegung');
INSERT INTO xplan_gml.enum_rp_verkehrstatus (wert, beschreibung) VALUES (7000, 'Korridor');
INSERT INTO xplan_gml.enum_rp_verkehrstatus (wert, beschreibung) VALUES (8000, 'Verlegung');
INSERT INTO xplan_gml.enum_rp_verkehrstatus (wert, beschreibung) VALUES (9999, 'SonstigerVerkehrStatus');

TRUNCATE xplan_gml.enum_rp_verkehrtypen;
INSERT INTO xplan_gml.enum_rp_verkehrtypen (wert, beschreibung) VALUES (1000, 'Schienenverkehr');
INSERT INTO xplan_gml.enum_rp_verkehrtypen (wert, beschreibung) VALUES (2000, 'Strassenverkehr');
INSERT INTO xplan_gml.enum_rp_verkehrtypen (wert, beschreibung) VALUES (3000, 'Luftverkehr');
INSERT INTO xplan_gml.enum_rp_verkehrtypen (wert, beschreibung) VALUES (4000, 'Wasserverkehr');
INSERT INTO xplan_gml.enum_rp_verkehrtypen (wert, beschreibung) VALUES (9999, 'SonstigerVerkehr');

TRUNCATE xplan_gml.enum_rp_wasserschutztypen;
INSERT INTO xplan_gml.enum_rp_wasserschutztypen (wert, beschreibung) VALUES (1000, 'Wasserschutzgebiet');
INSERT INTO xplan_gml.enum_rp_wasserschutztypen (wert, beschreibung) VALUES (2000, 'Grundwasserschutz');
INSERT INTO xplan_gml.enum_rp_wasserschutztypen (wert, beschreibung) VALUES (2001, 'Grundwasservorkommen');
INSERT INTO xplan_gml.enum_rp_wasserschutztypen (wert, beschreibung) VALUES (2002, 'Gewaesserschutz');
INSERT INTO xplan_gml.enum_rp_wasserschutztypen (wert, beschreibung) VALUES (3000, 'Trinkwasserschutz');
INSERT INTO xplan_gml.enum_rp_wasserschutztypen (wert, beschreibung) VALUES (4000, 'Trinkwassergewinnung');
INSERT INTO xplan_gml.enum_rp_wasserschutztypen (wert, beschreibung) VALUES (5000, 'Oberflaechenwasserschutz');
INSERT INTO xplan_gml.enum_rp_wasserschutztypen (wert, beschreibung) VALUES (6000, 'Heilquelle');
INSERT INTO xplan_gml.enum_rp_wasserschutztypen (wert, beschreibung) VALUES (7000, 'Wasserversorgung');
INSERT INTO xplan_gml.enum_rp_wasserschutztypen (wert, beschreibung) VALUES (9999, 'SonstigerWasserschutz');

TRUNCATE xplan_gml.enum_rp_wasserschutzzonen;
INSERT INTO xplan_gml.enum_rp_wasserschutzzonen (wert, beschreibung) VALUES (1000, 'Zone1');
INSERT INTO xplan_gml.enum_rp_wasserschutzzonen (wert, beschreibung) VALUES (2000, 'Zone2');
INSERT INTO xplan_gml.enum_rp_wasserschutzzonen (wert, beschreibung) VALUES (3000, 'Zone3');

TRUNCATE xplan_gml.enum_rp_wasserverkehrtypen;
INSERT INTO xplan_gml.enum_rp_wasserverkehrtypen (wert, beschreibung) VALUES (1000, 'Hafen');
INSERT INTO xplan_gml.enum_rp_wasserverkehrtypen (wert, beschreibung) VALUES (1001, 'Seehafen');
INSERT INTO xplan_gml.enum_rp_wasserverkehrtypen (wert, beschreibung) VALUES (1002, 'Binnenhafen');
INSERT INTO xplan_gml.enum_rp_wasserverkehrtypen (wert, beschreibung) VALUES (1003, 'Sportboothafen');
INSERT INTO xplan_gml.enum_rp_wasserverkehrtypen (wert, beschreibung) VALUES (1004, 'Laende');
INSERT INTO xplan_gml.enum_rp_wasserverkehrtypen (wert, beschreibung) VALUES (2000, 'Umschlagplatz');
INSERT INTO xplan_gml.enum_rp_wasserverkehrtypen (wert, beschreibung) VALUES (3000, 'SchleuseHebewerk');
INSERT INTO xplan_gml.enum_rp_wasserverkehrtypen (wert, beschreibung) VALUES (4000, 'Schifffahrt');
INSERT INTO xplan_gml.enum_rp_wasserverkehrtypen (wert, beschreibung) VALUES (4001, 'WichtigerSchifffahrtsweg');
INSERT INTO xplan_gml.enum_rp_wasserverkehrtypen (wert, beschreibung) VALUES (4002, 'SonstigerSchifffahrtsweg');
INSERT INTO xplan_gml.enum_rp_wasserverkehrtypen (wert, beschreibung) VALUES (4003, 'Wasserstrasse');
INSERT INTO xplan_gml.enum_rp_wasserverkehrtypen (wert, beschreibung) VALUES (5000, 'Reede');
INSERT INTO xplan_gml.enum_rp_wasserverkehrtypen (wert, beschreibung) VALUES (9999, 'SonstigerWasserverkehr');

TRUNCATE xplan_gml.enum_rp_wasserwirtschafttypen;
INSERT INTO xplan_gml.enum_rp_wasserwirtschafttypen (wert, beschreibung) VALUES (1000, 'Wasserleitung');
INSERT INTO xplan_gml.enum_rp_wasserwirtschafttypen (wert, beschreibung) VALUES (2000, 'Wasserwerk');
INSERT INTO xplan_gml.enum_rp_wasserwirtschafttypen (wert, beschreibung) VALUES (3000, 'StaudammDeich');
INSERT INTO xplan_gml.enum_rp_wasserwirtschafttypen (wert, beschreibung) VALUES (4000, 'Speicherbecken');
INSERT INTO xplan_gml.enum_rp_wasserwirtschafttypen (wert, beschreibung) VALUES (5000, 'Rueckhaltebecken');
INSERT INTO xplan_gml.enum_rp_wasserwirtschafttypen (wert, beschreibung) VALUES (6000, 'Talsperre');
INSERT INTO xplan_gml.enum_rp_wasserwirtschafttypen (wert, beschreibung) VALUES (7000, 'PumpwerkSchoepfwerk');
INSERT INTO xplan_gml.enum_rp_wasserwirtschafttypen (wert, beschreibung) VALUES (9999, 'SonstigeWasserwirtschaft');

TRUNCATE xplan_gml.enum_rp_wohnensiedlungtypen;
INSERT INTO xplan_gml.enum_rp_wohnensiedlungtypen (wert, beschreibung) VALUES (1000, 'Wohnen');
INSERT INTO xplan_gml.enum_rp_wohnensiedlungtypen (wert, beschreibung) VALUES (2000, 'Baugebietsgrenze');
INSERT INTO xplan_gml.enum_rp_wohnensiedlungtypen (wert, beschreibung) VALUES (3000, 'Siedlungsgebiet');
INSERT INTO xplan_gml.enum_rp_wohnensiedlungtypen (wert, beschreibung) VALUES (3001, 'Siedlungsschwerpunkt');
INSERT INTO xplan_gml.enum_rp_wohnensiedlungtypen (wert, beschreibung) VALUES (3002, 'Siedlungsentwicklung');
INSERT INTO xplan_gml.enum_rp_wohnensiedlungtypen (wert, beschreibung) VALUES (3003, 'Siedlungsbeschraenkung');
INSERT INTO xplan_gml.enum_rp_wohnensiedlungtypen (wert, beschreibung) VALUES (3004, 'Siedlungsnutzung');
INSERT INTO xplan_gml.enum_rp_wohnensiedlungtypen (wert, beschreibung) VALUES (4000, 'SicherungEntwicklungWohnstaetten');
INSERT INTO xplan_gml.enum_rp_wohnensiedlungtypen (wert, beschreibung) VALUES (5000, 'AllgemeinerSiedlungsbereichASB');
INSERT INTO xplan_gml.enum_rp_wohnensiedlungtypen (wert, beschreibung) VALUES (9999, 'SonstigeWohnenSiedlung');

TRUNCATE xplan_gml.enum_rp_zaesurtypen;
INSERT INTO xplan_gml.enum_rp_zaesurtypen (wert, beschreibung) VALUES (1000, 'Gruenzug');
INSERT INTO xplan_gml.enum_rp_zaesurtypen (wert, beschreibung) VALUES (2000, 'Gruenzaesur');
INSERT INTO xplan_gml.enum_rp_zaesurtypen (wert, beschreibung) VALUES (3000, 'Siedlungszaesur');

TRUNCATE xplan_gml.enum_rp_zeitstufen;
INSERT INTO xplan_gml.enum_rp_zeitstufen (wert, beschreibung) VALUES (1000, 'Zeitstufe1');
INSERT INTO xplan_gml.enum_rp_zeitstufen (wert, beschreibung) VALUES (2000, 'Zeitstufe2');

TRUNCATE xplan_gml.enum_rp_zentralerortsonstigetypen;
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (1000, 'Doppelzentrum');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (1100, 'Funktionsteilig');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (1101, 'MitOberzentralerTeilfunktion');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (1102, 'MitMittelzentralerTeilfunktion');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (1200, 'ImVerbund');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (1300, 'Kooperierend');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (1301, 'KooperierendFreiwillig');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (1302, 'KooperierendVerpflichtend');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (1400, 'ImVerdichtungsraum');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (1500, 'SiedlungsGrundnetz');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (1501, 'SiedlungsErgaenzungsnetz');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (1600, 'Entwicklungsschwerpunkt');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (1700, 'Ueberschneidungsbereich');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (1800, 'Ergaenzungsfunktion');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (1900, 'Nachbar');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (2000, 'MoeglichesZentrum');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (2100, 'FunktionsraumEindeutigeAusrichtung');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (2101, 'FunktionsraumBilateraleAusrichtung');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (2200, 'Kongruenzraum');
INSERT INTO xplan_gml.enum_rp_zentralerortsonstigetypen (wert, beschreibung) VALUES (9999, 'SonstigeSonstigerZentralerOrt');

TRUNCATE xplan_gml.enum_rp_zentralerorttypen;
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (1000, 'Oberzentrum');
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (1001, 'GemeinsamesOberzentrum');
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (1500, 'Oberbereich');
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (2000, 'Mittelzentrum');
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (2500, 'Mittelbereich');
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (3000, 'Grundzentrum');
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (3001, 'Unterzentrum');
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (3500, 'Nahbereich');
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (4000, 'Kleinzentrum');
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (5000, 'LaendlicherZentralort');
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (6000, 'Stadtrandkern1Ordnung');
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (6001, 'Stadtrandkern2Ordnung');
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (7000, 'VersorgungskernSiedlungskern');
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (8000, 'ZentralesSiedlungsgebiet');
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (9000, 'Metropole');
INSERT INTO xplan_gml.enum_rp_zentralerorttypen (wert, beschreibung) VALUES (9999, 'SonstigerZentralerOrt');

COMMIT;