BEGIN;
INSERT INTO xplan_gml.fp_detailzweckbestspielsportanlage
VALUES 
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','American Football','1000_01'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Badminton','1000_02'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Baseball','1000_03'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Basketball','1000_04'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Behindertensport','1000_05'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Bergsteigen','1000_06'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Boxen','1000_07'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Budo-Sportarten','1000_08'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Eissport','1000_09'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Fechten','1000_10'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Fußball','1000_11'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Golf','1000_12'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Gymnastik','1000_13'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Handball','1000_14'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Hockey','1000_15'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Kegelsport','1000_16'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Leichtathletik','1000_17'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Luftsport','1000_18'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Moderner Fünfkampf','1000_19'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Motorsport','1000_20'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Radsport','1000_21'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Reit- und Fahrsport','1000_22'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Ringen','1000_23'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Rollsport','1000_24'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Rugby','1000_25'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Schießsport','1000_26'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Schwerathletik','1000_27'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Schwimmsport','1000_28'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Squash','1000_29'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Tanzsport','1000_30'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Tennis','1000_31'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Tischtennis','1000_32'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Triathlon','1000_33'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Turnsport','1000_34'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Volleyball','1000_35'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Wassersport','1000_36'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Weitere Sportarten','1000_38'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailZweckbestSpielSportanlage','Wintersport','1000_37');
COMMIT;