BEGIN;
DELETE FROM xplan_gml.fp_detailartderbaulnutzung;
INSERT INTO xplan_gml.fp_detailartderbaulnutzung (codespace,value,id)
VALUES
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Allgemeine Siedlungsflaeche','9999_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Ausbildungszentrum','SON_9999_12'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Ausstellungs- und Mehrzweckfläche','SON_9999_14'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Autobahnmeisterei','SON_9999_6'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Autohof','SON_9999_45'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Bauflächen Dorf - Wohngebietscharakter','2000_2'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Bauhof','SON_9999_10'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Baumarkt','SON_1600_4'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Baustoffhandel','SON_1600_3'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Beherbergungsgewerbe, Hotelerie','SON_9999_13'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Behindertenwohnheim / Betreutes Wohnen','SON_2300_5'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Bekleidungsmarkt','SON_1600_9_2'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Biogasanlage','SON_1900_4'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Biogasanlage- Konzentrationszone','SON_1900_5'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Bootslager/Stellplaetze für Boote','SON_2200_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Busbahnhof','SON_9999_41'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Discothek','SON_9999_25'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','eingeschränktes Gewerbegebiet','1700_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Eingeschränktes Industriegebiet','1800_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Einkaufszentrum','SON_1600_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Einrichtungshaus','SON_1600_8'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Elektrofachmarkt','SON_1600_9_3'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Entsorgung','SON_9999_46'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Fachmarkt','SON_1600_9'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Fahrradtourismus','SON_2600_2'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Fahrsicherheitszentrum','SON_9999_47'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Festplatz','SON_2500_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Flugplatz / Landeplatz','SON_9999_7'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Forschung und Technologie','SON_2800_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Freizeiteinrichtung','SON_9999_24'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Freizeitpark, Erlebnispark, Themenpark','SON_9999_23'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Garagen','SON_9999_35'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Gartenbau','SON_9999_30'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Gartenmarkt/-fachhandel','SON_1600_5'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Gastronomie','SON_9999_37'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Gemischte Bauflaechen - Dienstleistungszentrum','2000_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Großhandel','SON_9999_38'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Hafenabhaengige Industriebetriebe','SON_1800_2'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Hospiz','SON_2300_11'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Hundebezogene Anlagen und Nutzungen','SON_9999_48'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Inklusives Wohnen','SON_2300_14'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Jugend- und Sportpark','SON_2200_6'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Jugendfreizeitanlage','SON_9999_15'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Jugendheim','SON_2300_13'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Katastrophenschutz','SON_9999_11'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Kfz-Handel und -Reparatur','SON_1600_12'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Kinderheim','SON_2300_12'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Kinderspielhaus / Indoor-Spielplatz','SON_9999_42'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Kleintierzucht','SON_9999_49'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Lagerhaltung','SON_9999_21'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Land- / Forstwirtschaftlicher Gutshof','SON_2100_2'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Landwirtschaftlicher Lohnbetrieb','SON_2100_3'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Lebensmittelherstellung und -verarbeitung','SON_9999_50'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Logistik','SON_9999_39'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Luftfracht','SON_9999_26'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Luftsport','SON_2200_7'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Mausoleum','SON_2500_3'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Medien','SON_9999_32'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Medizinisches Versorgungszentrum','SON_2300_6'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Medizintechnik','SON_9999_27'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Moebelfachmarkt','SON_1600_9_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Motorsport','SON_2200_8'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Museum','SON_2500_4'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Nahversorgung','SON_1600_7'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Parkhaus','SON_9999_8'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Parkplatz','SON_9999_34'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Pferdebezogene Anlagen und Nutzungen','SON_9999_44'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Privatschule','SON_9999_16'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','psychogeriatrisches Alten-Pflegeheim','SON_2300_4'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Recycling','SON_9999_18'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Reitsport Ferienanlage','SON_9999_28'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Rohstoffgewinnung und -verarbeitung','SON_9999_55'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','SB-Warenhaus','SON_1600_6'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Schießsport','SON_2200_3'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Schiffsanleger, Anleger, Anlegestelle, Landungssteg','SON_1800_4'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Schlachtbetrieb','SON_9999_40'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Schleuse','SON_1800_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Schloss','SON_2500_2'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Schullandheim','SON_2300_7'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Schwimmbad','SON_2200_2'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Seniorenresidenz/Seniorenwohnanlage','SON_2300_3'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Sicherheit und Ordnung','SON_9999_51'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Solarenergie / Photovoltaik','SON_1900_2'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Sonderbauflaeche für Landfahrer','SON_9999_2'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Sondergebiet Fachmarkt für nicht zentrenrelevante Sortimente','SON_1600_11'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Sondergebiet Freizeit','SON_9999_19'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Sondergebiet mit hohem Grünanteil','SON_9999_31'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Sonderpädagogische Einrichtung für Kinder und/oder Jugendliche','SON_2300_8'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','SOS-Kinderdorf','SON_2300_2'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Soziale Unterkunft','SON_2300_9'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Soziales und oekologisches Dorfprojekt','SON_9999_5'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Spielkasino','SON_9999_3'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Sportanlagen','SON_9999_22'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Tagungsstätte','SON_9999_54'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Tankstelle','SON_9999_9'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Tennis','SON_2200_5'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Teststrecke','SON_9999_57'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Tierhaltung','SON_2100_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Tierheim','SON_9999_17'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Trocknungsanlage','SON_2100_4'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Umweltbildungszentrum','SON_9999_36'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Verbrauchermarkt','SON_1600_10'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Vereinsbezogene Nutzung / Vereinsheim','SON_9999_52'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Verkehr','SON_9999_33'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Versorgung','SON_9999_29'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Veterinärmedizin','SON_9999_53'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Vollzugsanstalt / Justizvollzugsanstalt','SON_2720_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Waschstrasse','SON_9999_20'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Wassersport','SON_2200_4'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Wassertourismus','SON_2600_3'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Werkstatt für Menschen mit Behinderungen','SON_2300_10'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Windkraftanlage','SON_1900_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Windkraftanlage Konzentrationszone','SON_1900_3'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Wohnbauflaechen - parkartig','1000_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Wohnbauflaechen mit hohem Gruenanteil','1000_2'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Wohndorf für Menschen mit Behinderung','SON_2300_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Wohnen und Pferdehaltung','SON_9999_43'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Wohnfunktion in Kombination mit ergänzender Nutzung','SON_9999_56'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Wohnmobilstellplatz','SON_2600_1'),
('https://registry.gdi-de.org/codelist/de.xleitstelle.xplanung/FP_DetailArtDerBaulNutzung','Yachthafen, Marina','SON_1800_3'),

('https://testportal-plandigital.de/kvwmap','4-GenerationenPark','NI_1001'),
('https://testportal-plandigital.de/kvwmap','Gartencenter','NI_1002'),
('https://testportal-plandigital.de/kvwmap','Windenergie','NI_1003'),
('https://testportal-plandigital.de/kvwmap','Schank- und Speisewirtschaft mit Beherbergungsbetrieb','NI_1004'),
('https://testportal-plandigital.de/kvwmap','Naturkontaktstation','NI_1005'),
('https://testportal-plandigital.de/kvwmap','Ländliches Wohnen','NI_1006'),
('https://testportal-plandigital.de/kvwmap','Ländliches Wohnen','NI_1007'),
('https://testportal-plandigital.de/kvwmap','Hengstprüfanstalt','NI_1008'),
('https://testportal-plandigital.de/kvwmap','Lebensmittelmarkt','NI_1009'),
('https://testportal-plandigital.de/kvwmap','Kleintierzucht','NI_1010');


COMMIT;