<script type="text/javascript"><!--	function checkdate(vonJahr,vonMonat,vonTag,bisJahr,bisMonat,bisTag){		if(Number(vonJahr)*365 + Number(vonMonat)*12 + Number(vonTag) > Number(bisJahr)*365 + Number(bisMonat)*12 + Number(bisTag)){			document.GUI.bisTag.value = document.GUI.vonTag.value;			document.GUI.bisMonat.value = document.GUI.vonMonat.value;			document.GUI.bisJahr.value = document.GUI.vonJahr.value;		}	}//--></script><input type="hidden" name="go" value="Bauauskunft_Suche">
<h2><?php echo $this->titel; ?></h2>
<?php if ($this->Fehlermeldung!='') {
include(LAYOUTPATH."snippets/Fehlermeldung.php");
}
?>       
<table border="0" cellspacing="2" cellpadding="0" width=100%>  <tr>  	<td>&nbsp;</td>  </tr>  <tr>  	<td>&nbsp;</td>  </tr>  <tr>  	<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <td width=100%>    	<table cellspacing="2" cellpadding="2" style="border:1px solid #C3C7C3" width=100%>    		<tr>    			<td class="bold" colspan=2 style="border-bottom:1px solid #C3C7C3">Verwaltungsverfahren/Antragsart</td>    		</tr>    		<tr>    			<td width="22%" style="border-bottom:1px solid #C3C7C3">&nbsp;Bezeichnung:</td>    			<td style="border-bottom:1px solid #C3C7C3"><input type="text" name="bezeichnung" value="" size="30"></td>    		</tr>    		<tr>    			<td style="border-bottom:1px solid #C3C7C3">&nbsp;Aktenzeichen:</td>    			<td style="border-bottom:1px solid #C3C7C3"><input type="text" name="Aktenzeichen" value="" size="30"></td>    		</tr>    		<tr>    			<td style="border-bottom:1px solid #C3C7C3">&nbsp;Vorhaben:</td>    			<td style="border-bottom:1px solid #C3C7C3"><input type="text" name="Vorhaben" value="" size="30"></td>    		</tr>    		<tr>    			<td style="border-bottom:1px solid #C3C7C3">&nbsp;Betriebsart:</td>    			<td style="border-bottom:1px solid #C3C7C3"><input type="text" name="Betriebsart" value="" size="30"></td>    		</tr>    		<tr>    			<td>&nbsp;Eingang</td>    			<td style="border-left:1px solid #C3C7C3">    				<select size="Höhe" name="Tag">						<?  						for($i=1; $i<32; $i++){							echo '<option';							if(date("d") == $i){								echo ' selected="selected"';							}							echo '>'.$i.'</option>';						}						?>					</select>					<select size="Höhe" name="Monat">						<?  						for($i=1; $i<13; $i++){							echo '<option';							if(date("m") == $i){								echo ' selected="selected"';							}							echo '>'.$i.'</option>';						}						?>					</select>					<select size="Höhe" name="Jahr">						<?  						for($i=1800; $i<2006; $i++){							echo '<option';							if(date("Y") == $i){								echo ' selected="selected"';							}							echo '>'.$i.'</option>';						}						?>					</select>				</td>    		</tr>    	</table> 
    </td>    <td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
  </tr>  
  <tr>  	<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> 
    <td width=100%>    	<table cellspacing="2" cellpadding="2" style="border:1px solid #C3C7C3" width=100%>    		<tr>    			<td class="bold" colspan="5" style="border-bottom:1px solid #C3C7C3">Antragsteller</td>    		</tr>    		<tr>    			<td width="22%" style="border-bottom:1px solid #C3C7C3">&nbsp;Name:</td>    			<td colspan="4" style="border-bottom:1px solid #C3C7C3"><input type="text" name="Name" value="" size="30"></td>    		</tr>    		<tr>    			<td style="border-bottom:1px solid #C3C7C3">&nbsp;Vorname:</td>    			<td colspan="4" style="border-bottom:1px solid #C3C7C3"><input type="text" name="Vorname" value="" size="30"></td>    		</tr>    		<tr>    			<td style="border-bottom:1px solid #C3C7C3">&nbsp;Strasse:</td>    			<td style="border-bottom:1px solid #C3C7C3"><input type="text" name="Strasse" value="" size="30"></td>    			<td style="border-bottom:1px solid #C3C7C3">&nbsp;Nr:</td>    			<td style="border-bottom:1px solid #C3C7C3"><input type="text" name="Hausnummer" value="" size="2"></td>    			<td style="border-bottom:1px solid #C3C7C3" width="20%">&nbsp;</td>    		</tr>    		<tr>    			<td width="100%" colspan="5">    				<table width="100%" cellpadding="0" cellspacing="0" border="0">    					<tr>    						<td width="22%">&nbsp;PLZ:</td>			    			<td style="border-left:1px solid #C3C7C3"><input type="text" name="PLZ" value="" size="3"></td>			    			<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Ort:&nbsp;</td>			    			<td style="border-left:1px solid #C3C7C3"><input type="text" name="Ort" value="" size="25"></td>			    			<td width="14%">&nbsp;</td>		    					</tr>    				</table>    			</td>    		</tr>    	</table>	</td>	<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>  </tr> 
  <tr>  	<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td> 
    <td width="100%">    	<table cellspacing="2" cellpadding="2" style="border:1px solid #C3C7C3" width="100%">    		<tr>    			<td class="bold" colspan=2 style="border-bottom:1px solid #C3C7C3">Grundstück</td>    		</tr>    		<tr>    			<td width="22%" style="border-bottom:1px solid #C3C7C3">&nbsp;Gemarkung:</td>    			<td style="border-bottom:1px solid #C3C7C3"><input type="text" name="bezeichnung" value="" size="30"></td>    		</tr>    		<tr>    			<td style="border-bottom:1px solid #C3C7C3">&nbsp;Flur:</td>    			<td style="border-bottom:1px solid #C3C7C3"><input type="text" name="bezeichnung" value="" size="30"></td>    		</tr>    		<tr>    			<td>&nbsp;Flurstück:</td>    			<td style="border-left:1px solid #C3C7C3"><input type="text" name="bezeichnung" value="" size="30"></td>    		</tr>    	</table>	</td>	<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>  </tr>  <tr>  	<td>&nbsp;</td>  </tr>  <tr>  	<td>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>  	<td width="100%"">  		<table cellspacing="2" cellpadding="2" style="border:1px solid #C3C7C3" width=100%>  			<tr>  				<td width="22%"">Datei anhängen:&nbsp;&nbsp;&nbsp;<input type="file"></td>  			</tr>  		</table>  	</td>  </tr>  <tr>  	<td>&nbsp;</td>  </tr>
  <tr align="center"> 
    <td colspan="2"> 
 		<input type="submit" name="go_plus" value="Abbrechen">&nbsp;<input type="submit" name="aktualisieren" value="Neu">&nbsp;<input type="submit" name="aktualisieren" value="Aktualisieren">&nbsp;<input type="submit" name="go_plus" value="Senden">
    </td>
  </tr>  <tr>  	<td>&nbsp;</td>  </tr> 
</table>
