BEGIN;
  ALTER TABLE kvwmap.user
    DROP CONSTRAINT IF EXISTS fk_stelle_id,
    ADD CONSTRAINT fk_stelle_id FOREIGN KEY (stelle_id) REFERENCES kvwmap.stelle(id) ON UPDATE CASCADE ON DELETE NO ACTION;
COMMIT;