BEGIN;

ALTER TABLE probaug.bau_akten ADD COLUMN feld27 CHARACTER VARYING(60);
ALTER TABLE probaug.bau_akten ADD COLUMN feld28 CHARACTER VARYING(60);
ALTER TABLE probaug.bau_akten ADD COLUMN feld29 CHARACTER VARYING(60);
ALTER TABLE probaug.bau_akten ADD COLUMN feld30 CHARACTER VARYING(60);
ALTER TABLE probaug.bau_akten ADD COLUMN feld31 CHARACTER VARYING(60);
ALTER TABLE probaug.bau_akten ADD COLUMN feld32 CHARACTER VARYING(60);
ALTER TABLE probaug.bau_akten ADD COLUMN feld33 CHARACTER VARYING(100);
ALTER TABLE probaug.bau_akten ADD COLUMN feld34 CHARACTER VARYING(100);
ALTER TABLE probaug.bau_akten ADD COLUMN feld35 CHARACTER VARYING(100);
ALTER TABLE probaug.bau_akten ADD COLUMN feld36 CHARACTER VARYING(60);
ALTER TABLE probaug.bau_akten ADD COLUMN feld37 CHARACTER VARYING(60);
ALTER TABLE probaug.bau_akten ADD COLUMN feld38 CHARACTER VARYING(10);

COMMIT;
