BEGIN;

ALTER TABLE alkis.ax_punktortau ALTER COLUMN processstep_description RENAME TO processstep_ax_datenerhebung_punktort;
ALTER TABLE alkis.ax_punktortau ALTER COLUMN herkunft_source_source_description RENAME TO herkunft_source_source_ax_datenerhebung_punktort;

ALTER TABLE alkis.ax_punktortag ALTER COLUMN processstep_description RENAME TO processstep_ax_datenerhebung_punktort;
ALTER TABLE alkis.ax_punktortag ALTER COLUMN herkunft_source_source_description RENAME TO herkunft_source_source_ax_datenerhebung_punktort;

ALTER TABLE alkis.ax_punktortta ALTER COLUMN processstep_description RENAME TO processstep_ax_datenerhebung_punktort;
ALTER TABLE alkis.ax_punktortta ALTER COLUMN herkunft_source_source_description RENAME TO herkunft_source_source_ax_datenerhebung_punktort;

COMMIT;
