SET search_path = alkis, public;
DROP TABLE ks_einrichtunginoeffentlichenbereichen;
DROP TABLE ks_bauwerkanlagenfuerverundentsorgung;
DROP TABLE ks_sonstigesbauwerk;
DROP TABLE ks_einrichtungimstrassenverkehr;
DROP TABLE ks_verkehrszeichen;
DROP TABLE ks_einrichtungimbahnverkehr;
DROP TABLE ks_bauwerkimgewaesserbereich; 
DROP TABLE ks_vegetationsmerkmal;
DROP TABLE ks_bauraumoderbodenordnungsrecht;
DROP TABLE ks_kommunalerbesitz;