BEGIN;

CREATE TABLE alkis.n_begriffsbestimmungen (
	kennung int4 NOT NULL,
	bezeichnung varchar(100) NOT NULL,
	begriffsbestimmung text
);
ALTER TABLE alkis.n_begriffsbestimmungen ADD CONSTRAINT n_begriffsbestimmungen_pk PRIMARY KEY (kennung);

INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('10000000', 'Siedlung', 'Der Nutzungsartenbereich "Siedlung" beinhaltet die bebauten und nicht bebauten Flächen, die durch die Ansiedlung von Menschen geprägt werden oder zur Ansiedlung beitragen.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('11000000', 'Wohnbaufläche', '"Wohnbaufläche" ist eine baulich geprägte Fläche einschließlich der mit ihr im Zusammenhang stehenden Freiflächen (z.B. Vorgärten, Ziergärten, Zufahrten, Stellplätze und Hofraumflächen), die ausschließlich oder vorwiegend dem Wohnen dient.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('12000000', 'Industrie- und Gewerbefläche', '"Industrie- und Gewerbefläche" ist eine Fläche, auf der sich Industrie, Gewerbe-, Handels- und Dienstleistungsunternehmen sowie deren Betriebsflächen befinden.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('12010000', 'Industrie und Gewerbe', '"Industrie- und Gewerbe" bezeichnet Flächen, auf denen vorwiegend Industrie- und Gewerbebetriebe vorhanden sind. Darin sind Gebäude- und Freiflächen und die Betriebsflächen Lagerfläche enthalten.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('12020000', 'Handel und Dienstleistung', '"Handel und Dienstleistung" bezeichnet eine Fläche, auf der vorwiegend Gebäude stehen, in denen Handels- und/oder Dienstleistungsbetriebe ansässig sind. Dazu gehören auch Flächen zur Beherbergung, Restauration und/oder Vergnügung.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('12030000', 'Versorgungsanlage', '"Versorgungsanlage" bezeichnet eine Fläche, auf der vorwiegend Anlagen und Gebäude zur Versorgung mit Elektrizität, Wärme, Wasser, Öl, Gas oder zur elektronischen Informationsübertragung vorhanden sind.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('12040000', 'Entsorgung', '"Entsorgung" bezeichnet eine Fläche, auf der vorwiegend Anlagen und Gebäude zur Verwertung und Entsorgung von Abwasser und festen Abfallstoffen vorhanden sind.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('13000000', 'Halde', '"Halde" ist eine Fläche, auf der Material langfristig gelagert wird und beschreibt die auch im Relief zu modellierende tatsächliche Aufschüttung. Dauerhaft anders genutzte Halden werden als Objekte entsprechend der tatsächlichen Nutzung erfasst.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('14000000', 'Bergbaubetrieb', '"Bergbaubetrieb" ist eine Fläche, die für die Förderung des Abbauguts unter Tage genutzt wird.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('15000000', 'Tagebau, Grube, Steinbruch', '"Tagebau, Grube, Steinbruch" ist eine Fläche, auf der oberirdisch Bodenmaterial abgebaut und für die Förderung des oberirdischen Abbaugutes genutzt wird. Rekultivierte Tagebaue, Gruben, Steinbrüche werden als Objekte entsprechend der vorhandenen Nutzung erfasst.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('16000000', 'Fläche gemischter Nutzung', '"Fläche gemischter Nutzung" ist eine bebaute Fläche einschließlich der mit ihr im Zusammenhang stehenden Freifläche (Hofraumfläche, Hausgarten), auf der keine Art der baulichen Nutzung vorherrscht. Solche Flächen sind insbesondere ländlich-dörflich geprägte Flächen mit land- und forstwirtschaftlichen Betrieben, Wohngebäuden u.a. sowie städtisch geprägte Kerngebiete mit Handelsbetrieben und zentralen Einrichtungen für die Wirtschaft und die Verwaltung.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('16010000', 'Landwirtschaftliche Betriebsfläche', '"Landwirtschaftliche Betriebsfläche" ist eine bebaute oder unbebaute Fläche, die dem  landwirtschaftlichen Betrieb ohne eine Wohnnutzung dient.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('16030000', 'Fischereiwirtschaftsfläche', '"Fischereiwirtschaftsfläche" bezeichnet Flächen/Areale, die dem (gewerblichen) Fangen oder Züchten von Fischen und anderen Wassertieren/ im Wasser lebenden Organismen zur Nahrungsgewinnung und Weiterverarbeitung dienen.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('16720000', 'Gebäude- und Freifläche Land- und Forstwirtschaft', '"Gebäude- und Freifläche Land- und Forstwirtschaft" bezeichnet eine Fläche, die vorwiegend der Land- und Forstwirtschaft dient, einschließlich des Wohnteils.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('17000000', 'Fläche besonderer funktionaler Prägung', '"Fläche besonderer funktionaler Prägung" ist eine baulich geprägte Fläche einschließlich der mit ihr im Zusammenhang stehenden Freifläche, auf denen vorwiegend Gebäude und/oder Anlagen zur Erfüllung öffentlicher Zwecke oder historische Anlagen vorhanden sind.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('17010000', 'Öffentliche Zwecke', '"Öffentliche Zwecke" bezeichnet eine Fläche, die vorwiegend der Erfüllung öffentlicher Aufgaben und dem Gemeinwesen dient.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('18000000', 'Sport-, Freizeit- und Erholungsfläche', '"Sport-, Freizeit- und Erholungsfläche" ist eine bebaute oder unbebaute Fläche, die dem Sport, der Freizeitgestaltung oder der Erholung dient.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('18010000', 'Sportanlage', '"Sportanlage" ist eine Fläche mit Bauwerken und Einrichtungen, die zur Ausübung von (Wettkampf-)Sport und für Zuschauer bestimmt ist.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('18020000', 'Freizeitanlage', '"Freizeitanlage" bezeichnet eine Fläche, die vorwiegend der Freizeitgestaltung oder dazu dient, Tiere zu zeigen.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('18030000', 'Erholungsfläche', '"Erholungsfläche" ist eine Fläche mit Bauwerken und Einrichtungen, die zur Erholung bestimmt ist.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('18040000', 'Grünanlage', '"Grünanlage" ist in erster Linie eine Anlage mit Bäumen, Sträuchern, Rasenflächen, Blumenrabatten und Wegen. Sie dient der Erholung einschließlich spielerischer Aktivitäten oder erfüllt stadtgestalterische Aufgaben.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('19000000', 'Friedhof', '"Friedhof" ist eine Landfläche, die zur Bestattung dient oder gedient hat, sofern die Zuordnung zu Grünanlage nicht zutreffender ist. Waldbestattungsflächen werden der Nutzungsart Wald zugeordnet.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('20000000', 'Verkehr', 'Der Nutzungsartenbereich "Verkehr" enthält die bebauten und nicht bebauten Flächen, die dem Verkehr dienen.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('21000000', 'Straßen- und Wegeverkehr', NULL);
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('21010000', 'Straßenverkehr', '"Straßenverkehr" umfasst alle für die bauliche Anlage Straße erforderlichen Flächen und die dem Straßenverkehr dienenden bebauten und unbebauten Flächen.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('21020000', 'Weg', '"Weg" umfasst alle Flächen, die zum Befahren und/oder Begehen vorgesehen sind. Zur Wegfläche gehören auch Seitenstreifen und Gräben zur Wegentwässerung.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('21030000', 'Platz', '"Platz" ist eine Verkehrsfläche in Ortschaften oder eine ebene, befestigte oder unbefestigte Fläche, die bestimmten Zwecken dient (z.B. für Verkehr, Parkplätze, Märkte, Festveranstaltungen).');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('22000000', 'Bahnverkehr', '"Bahnverkehr" umfasst alle für den Schienenverkehr erforderlichen Flächen und die dem Schienenverkehr dienenden bebauten und unbebauten Flächen.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('23000000', 'Flugverkehr', '"Flugverkehr" umfasst die baulich geprägte Fläche und die mit ihr in Zusammenhang stehende Freifläche, die ausschließlich oder vorwiegend dem Flugverkehr dient.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('24000000', 'Schiffsverkehr', '"Schiffsverkehr" umfasst die baulich geprägte Fläche und die mit ihr in Zusammenhang stehende Freifläche, die ausschließlich oder vorwiegend dem Schiffsverkehr dient.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('30000000', 'Vegetation', 'Der Nutzungsartenbereich "Vegetation" umfasst die Flächen außerhalb der Ansiedlungen, die durch land- oder forstwirtschaftliche Nutzung, durch natürlichen Bewuchs oder dessen Fehlen geprägt werden.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('31000000', 'Landwirtschaft', '"Landwirtschaft" ist eine Fläche für den Anbau von Feldfrüchten sowie eine Fläche, die beweidet und gemäht werden kann, einschließlich der mit besonderen Pflanzen angebauten Flächen (einschließlich landwirtschaftlichen Brachlands).');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('31010000', 'Ackerland', '"Ackerland" ist eine Fläche für den Anbau von Feldfrüchten (z.B. Getreide, Hülsenfrüchte, Hackfrüchte) und Beerenfrüchten (z.B. Erdbeeren).');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('31020000', 'Grünland', '"Grünland" ist eine Grasfläche, die gemäht oder beweidet wird.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('31030000', 'Gartenbauland', '"Gartenbauland" ist eine Fläche, die dem gewerbsmäßigen Anbau von Gartengewächsen (Gemüse, Obst und Blumen) sowie für die Aufzucht von Kulturpflanzen dient.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('31040000', 'Rebfläche', '"Rebflächen" ist eine mit speziellen Vorrichtungen ausgestattete Agrarfläche, auf der Weinstöcke angepflanzt sind.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('31050000', 'Obst- und Nussplantage', '"Obst- und Nussplantage" ist eine Fläche, die vorwiegend dem Intensivanbau dient und mit Obst-, Nussbäumen oder -sträuchern bepflanzt ist. Im Unterschied zu Streuobst handelt es sich hierbei um gleichmäßige und dichter angelegte Monokulturen.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('31060000', 'Weihnachtsbaumkultur', '"Weihnachtsbaumkultur" bezeichnet eine landwirtschaftliche Fläche, die vorrangig mit Weihnachtsbäumen bepflanzt ist.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('31100000', 'Kurzumtriebsplantage', '"Kurzumtriebsplantagen" sind Flächen, auf denen Baumarten mit dem Ziel baldiger Holzentnahme angepflanzt werden und deren Bestände eine Umtriebszeit von nicht länger als 20 Jahren haben.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('31200000', 'Brachland', '"Brachland" ist eine Fläche der Landwirtschaft, die seit längerem nicht mehr zu Produktionszwecken genutzt wird.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('32000000', 'Wald', '"Wald" ist eine Fläche, die mit Forstpflanzen (Waldbäume und Waldsträucher) bestockt ist, mit mindestens 0,2 ha Grundfläche. Ansonsten gelten die Begriffsbestimmungen des Waldgesetzes für das Land Mecklenburg-Vorpommern (Landeswaldgesetz – LWaldG) in der aktuellen Fassung.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('32010000', 'Forstwirtschaftsfläche', '"Forstwirtschaftsfläche" bezeichnet eine Waldfläche, mit oder ohne Bäume, welche forstwirtschaftlich genutzt wird. Hierzu zählen keine Kurzumtriebsplantagen.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('32030000', 'Waldbestattungsfläche', '"Waldbestattungsfläche" ist eine Fläche im Wald, die zur Bestattung dient oder gedient hat.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('33000000', 'Gehölz', '"Gehölz" ist eine Fläche, die mit einzelnen Bäumen, Baumgruppen, Büschen, Hecken und Sträuchern bestockt ist.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('34000000', 'Heide', '"Heide" ist eine Fläche mit typischen Sträuchern, Gräsern und geringwertigem Baumbestand.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('35000000', 'Moor', '"Moor" ist eine unkultivierte Fläche, deren obere Schicht aus vertorften oder zersetzten Pflanzenresten besteht.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('36000000', 'Sumpf', '"Sumpf" ist ein wassergesättigtes, zeitweise unter Wasser stehendes Gelände.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('37000000', 'Unland, Vegetationslose Fläche', '"Unland, Vegetationslose Fläche" ist eine Fläche die nicht dauerhaft landwirtschaftlich genutzt wird, wie z. B. Fels-, Sand- oder Eisflächen, Uferstreifen längs von Gewässern und Sukzessionsflächen.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('37010000', 'Vegetationslose Fläche', '"Vegetationslose Fläche" ist eine Fläche ohne nennenswerten Bewuchsaufgrund besonderer Bodenbeschaffenheit."');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('37020000', 'Gewässerbegleitfläche', '"Gewässerbegleitfläche" bezeichnet eine bebaute oder unbebaute Fläche, die einem Gewässer zugeordnet wird. Die Gewässerbegleitfläche ist nicht Bestandteil der Gewässerfläche.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('37040000', 'Naturnahe Fläche', '"Naturnahe Fläche" ist eine nicht zum Anbau von Kulturpflanzen genutzte Fläche, die mit Pflanzen bewachsen ist.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('40000000', 'Gewässer', 'Der Nutzungsartenbereich "Gewässer" umfasst die mit Wasser bedeckten Flächen.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('41000000', 'Fließgewässer', '"Fließgewässer" ist ein geometrisch begrenztes, auf dem Festland fließendes Gewässer, das die Wassermengen sammelt, die als Niederschläge auf die Erdoberfläche fallen oder in Quellen austreten, und in ein anderes Gewässer, ein Meer oder in einen See transportiert werden oder in einem System von natürlichen oder künstlichen Bodenvertiefungen verlaufendes Wasser, das zur Be- und Entwässerung an- oder abgeleitet wird oder ein geometrisch begrenzter, für die Schifffahrt angelegter künstlicher Wasserlauf, der in einem oder mehreren Abschnitten die jeweils gleiche Höhe des Wasserspiegels besitzt.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('41010000', 'Fluss', '"Fluss" ist ein natürliches, fließendes Gewässer (ggf. auch mit begradigten, kanalisierten Teilstücken), das wegen seiner Größe und Bedeutung im allgemeinen Sprachgebrauch als Fluss angesprochen wird.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('41020000', 'Kanal', '"Kanal" bezeichnet einen künstlich angelegten Wasserlauf.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('41030000', 'Graben', '"Graben" ist ein ständig oder zeitweise fließendes, künstlich angelegtes oder natürliches Gewässer, das im allgemeinen Sprachgebrauch als Graben anzusehen ist.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('41040000', 'Bach', '"Bach" ist ein natürliches, fließendes Gewässer, das wegen seiner geringen Größe und Bedeutung im allgemeinen Sprachgebrauch als Bach anzusehen ist.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('42000000', 'Hafenbecken', '"Hafenbecken" ist ein natürlicher oder künstlich angelegter oder abgetrennter Teil eines Gewässers, in dem Schiffe beund entladen werden.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('43000000', 'Stehendes Gewässer', '"Stehendes Gewässer" ist eine natürliche oder künstliche mit Wasser gefüllte, allseitig umschlossene Hohlform der Erdoberfläche ohne unmittelbare Verbindung mit dem Meer.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('43010000', 'See', '"See" ist eine natürliche oder künstlich angelegte, größere, stehende oder nahezu stehende Wasserfläche, die im allgemeinen Sprachgebrauch als See anzusehen ist.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('43020000', 'Teich', '"Teich" ist eine natürliche oder künstlich angelegte, stehende oder nahezustehende Wasserfläche, die im allgemeinen Sprachgebrauch als Teich anzusehen ist.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('43030000', 'Sonstiges [Stehendes Gewässer]', '"Sonstiges Stehendes Gewässer" bedeutet, dass die Funktion des Stehenden Gewässers bekannt, aber nicht in der Werteliste aufgeführt ist. Hierzu zählen die Sölle.');
INSERT INTO alkis.n_begriffsbestimmungen (kennung, bezeichnung, begriffsbestimmung) VALUES ('44000000', 'Meer', '"Meer" ist die das Festland umgebende Wasserfläche.');


COMMIT;
