BEGIN;

TRUNCATE alkis.n_untergliederung2;

INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 1, 1, 'Nahrungs-, Futter-, Genussmittel');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 1, 2, 'Textil, Bekleidung, Lederwaren');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 1, 3, 'Holz-, Naturfaser-, Verpackungsprodukte');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 1, 4, 'Print-, Audio-, Videoprodukte');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 1, 5, 'Mineralölverarbeitung, Kokerei');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 1, 6, 'Chemie-, Pharma-, Kunststoffprodukte');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 1, 7, 'Mineralische Bau- und Werkstoffe');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 1, 8, 'Metallerzeugung und -verarbeitung');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 1, 9, 'Technik, Elektrik, Elektronik');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 1, 10, 'Maschinenbau');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 1, 11, 'Fahrzeugbau');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 1, 12, 'Möbel und sonstige Konsumgüter');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 2, 1, 'Baustoffe');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 2, 2, 'Kohle, Erz und Salz');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 2, 3, 'Öl');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 2, 4, 'Erdreich');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 2, 5, 'Schutt');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 2, 6, 'Schlacke');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 2, 7, 'Abraum');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 2, 8, 'Schrott, Altmaterial');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 2, 9, 'Gas');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 1, 2, 10, 'Sonstiges');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 1, 1, 'Erdöl');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 1, 2, 'Erdgas');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 1, 3, 'Sole, Lauge');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 1, 4, 'Kohlensäure');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 1, 5, 'Erdwärme');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 1, 71, 'Gebäude- und Freifläche Förderanlage');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 2, 71, 'Gebäude- und Freifläche Versorgungsanlage, Wasser');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 2, 81, 'Betriebsfläche Versorgungsanlage, Wasser');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 3, 1, 'Wasser');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 3, 2, 'Kernkraft');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 3, 3, 'Sonne');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 3, 4, 'Wind');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 3, 5, 'Gezeiten');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 3, 6, 'Erdwärme');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 3, 7, 'Verbrennung');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 3, 8, 'Kohle');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 3, 9, 'Öl');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 3, 10, 'Gas');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 3, 11, 'Müll, Abfall');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 3, 12, 'Biomasse');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 3, 71, 'Gebäude- und Freifläche Versorgungsanlage, Elektrizität');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 3, 81, 'Betriebsfläche Versorgungsanlage, Elektrizität');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 5, 71, 'Gebäude- und Freifläche Versorgungsanlage, Öl');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 5, 81, 'Betriebsfläche Versorgungsanlage, Öl');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 6, 71, 'Gebäude- und Freifläche Versorgungsanlage, Gas');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 6, 81, 'Betriebsfläche Versorgungsanlage, Gas');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 7, 2, 'Kernkraft');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 7, 3, 'Sonne');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 7, 6, 'Erdwärme');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 7, 7, 'Verbrennung');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 7, 8, 'Kohle');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 7, 9, 'Öl');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 7, 10, 'Gas');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 7, 11, 'Müll, Abfall');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 7, 12, 'Biomasse');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 7, 71, 'Gebäude- und Freifläche Versorgungsanlage, Wärme');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 7, 81, 'Betriebsfläche Versorgungsanlage, Wärme');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 8, 71, 'Gebäude- und Freifläche Versorgungsanlage, Funk- und Fernmeldewesen');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 3, 8, 81, 'Betriebsfläche Versorgungsanlage, Funk- und Fernmeldewesen');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 4, 1, 71, 'Gebäude- und Freifläche Entsorgungsanlage, Abwasserbeseitigung');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 4, 1, 81, 'Betriebsfläche Entsorgungsanlage, Abwasserbeseitigung');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 4, 2, 71, 'Gebäude- und Freifläche Entsorgungsanlage, Abfallbeseitigung');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 4, 2, 81, 'Betriebsfläche Entsorgungsanlage, Abfallbeseitigung');
INSERT INTO alkis.n_untergliederung2 VALUES (12, 4, 2, 82, 'Betriebsfläche Entsorgungsanlage, Schlamm');
INSERT INTO alkis.n_untergliederung2 VALUES (18, 2, 1, 71, 'Gebäude- und Freifläche Freizeit, Zoologie');
INSERT INTO alkis.n_untergliederung2 VALUES (18, 3, 2, 71, 'Gebäude- und Freifläche Erholung, Bad');
INSERT INTO alkis.n_untergliederung2 VALUES (18, 3, 3, 71, 'Gebäude- und Freifläche Erholung, Camping');
INSERT INTO alkis.n_untergliederung2 VALUES (18, 4, 3, 71, 'Gebäude- und Freifläche Grünanlage, Botanik');
INSERT INTO alkis.n_untergliederung2 VALUES (21, 1, 2, 1, 'Straßenentwässerungsanlage');
INSERT INTO alkis.n_untergliederung2 VALUES (21, 2, 1, 1, 'Hauptwirtschaftsweg');
INSERT INTO alkis.n_untergliederung2 VALUES (21, 2, 1, 2, 'Wirtschaftsweg');
INSERT INTO alkis.n_untergliederung2 VALUES (43, 1, 1, 1, 'Speicherbecken');

COMMIT;
